/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { HealthController } from '../src';
import { testClient } from './testClient.js';
import { expectHeadersToMatch, makeApiCall } from './testHelper.js';

describe('HealthController', () => {
  let controller : HealthController;

  beforeAll(() => {
    controller = new HealthController(testClient);
  });

  it('should Test getHealth', async () => {
    const response = await makeApiCall(() => controller.getHealth());

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);
  });
});
