/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  CreateTenantRequest,
  CreateTenantResponse,
  TenantResponse,
  TenantsController,
  UpdateTenantRequest,
  UpdateTenantResponse,
} from '../src';
import { testClient } from './testClient.js';
import {
  expectHeadersToMatch,
  expectMatchingWithOptions,
  makeApiCall,
} from './testHelper.js';

describe('TenantsController', () => {
  let controller : TenantsController;

  beforeAll(() => {
    controller = new TenantsController(testClient);
  });

  it('should Test create1', async () => {
    const authorization = 'Bearer <token>';

    const body: CreateTenantRequest = {
      businessLegalName: 'Acme Corporation',
      businessDba: 'Acme Co',
      businessAddressCountry: 'US',
      businessStreetAddress1: '123 Corp Blvd',
      businessStreetAddress2: 'Suite 100',
      businessCity: 'New York',
      businessState: 'NY',
      businessLegalEntityIdentifier: '123456789',
      webhookUrl: 'https://example.com/webhooks/tesser',
    };

    const response = await makeApiCall(
      () => controller.create1(authorization, body)
    );

    expect(response.statusCode).toBe(201);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: CreateTenantResponse = {
      data: {
        id: '4e8c2a6f-1b9d-4f37-a5e0-7c3b8d2f1a9e',
        workspaceId: 'b53f6690-3242-4942-9907-885779632832',
        businessLegalName: 'Acme Corporation',
        businessDba: 'Acme Co',
        businessAddressCountry: 'US',
        businessStreetAddress1: '123 Corp Blvd',
        businessStreetAddress2: 'Suite 100',
        businessCity: 'New York',
        businessState: 'NY',
        businessLegalEntityIdentifier: '9876543210',
        country: 'US',
        webhookUrl: 'https://acme.com/webhooks/tesser',
        createdAt: '2024-01-15T10:30:00.000Z',
        updatedAt: '2024-01-15T10:30:00.000Z',
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test findOne1', async () => {
    const id = '4e8c2a6f-1b9d-4f37-a5e0-7c3b8d2f1a9e';

    const authorization = 'Bearer <token>';

    const response = await makeApiCall(
      () => controller.findOne1(id, authorization, undefined)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: TenantResponse = {
      data: {
        id: '4e8c2a6f-1b9d-4f37-a5e0-7c3b8d2f1a9e',
        workspaceId: 'b53f6690-3242-4942-9907-885779632832',
        businessLegalName: 'Acme Corporation',
        businessDba: 'Acme Co',
        businessAddressCountry: 'US',
        businessStreetAddress1: '123 Corp Blvd',
        businessStreetAddress2: 'Suite 100',
        businessCity: 'New York',
        businessState: 'NY',
        businessLegalEntityIdentifier: '9876543210',
        country: 'US',
        webhookUrl: 'https://acme.com/webhooks/tesser',
        createdAt: '2024-01-15T10:30:00.000Z',
        updatedAt: '2024-01-15T10:30:00.000Z',
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });

  it('should Test update2', async () => {
    const id = '4e8c2a6f-1b9d-4f37-a5e0-7c3b8d2f1a9e';

    const authorization = 'Bearer <token>';

    const body: UpdateTenantRequest = {
      businessDba: 'Acme Corp Updated',
      webhookUrl: 'https://acme.com/webhooks/tesser',
    };

    const response = await makeApiCall(
      () => controller.update2(id, authorization, body)
    );

    expect(response.statusCode).toBe(200);

    const expectedHeaders = { 'Content-Type': ['application/json', true] };

    expectHeadersToMatch(response.headers, expectedHeaders);

    const expected: UpdateTenantResponse = {
      data: {
        id: '4e8c2a6f-1b9d-4f37-a5e0-7c3b8d2f1a9e',
        workspaceId: 'b53f6690-3242-4942-9907-885779632832',
        businessLegalName: 'Acme Corporation',
        businessDba: 'Acme Corp Updated',
        businessAddressCountry: 'US',
        businessStreetAddress1: '123 Corp Blvd',
        businessStreetAddress2: 'Suite 100',
        businessCity: 'New York',
        businessState: 'NY',
        businessLegalEntityIdentifier: '9876543210',
        country: 'US',
        webhookUrl: 'https://acme.com/webhooks/tesser',
        createdAt: '2024-01-15T10:30:00.000Z',
        updatedAt: '2024-03-01T12:00:00.000Z',
      },
    };

    expect(response.result).not.toBeNull();
    expectMatchingWithOptions(
      expected,
      response.result,
      { allowExtra: true, isOrdered: false, checkValues: false }
    );
  });
});
