/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Client, Configuration, Environment } from '../src';

export const testClient = new Client(createConfigurationFromEnvironment());

function createConfigurationFromEnvironment(): Partial<Configuration> {
  const config: Partial<Configuration> = {};

  const environment = process.env.TESSER_API_V_1_LIB_ENVIRONMENT;
  const timeout = process.env.TESSER_API_V_1_LIB_TIMEOUT;
  const accessToken = process.env.TESSER_API_V_1_LIB_ACCESS_TOKEN;

  if (environment !== undefined) {
    config.environment = environment as Environment;
  }

  if (timeout !== undefined && timeout !== '') {
    config.timeout = parseInt(timeout);
  }

  if (accessToken !== undefined) {
    config.bearerAuthCredentials = { accessToken: accessToken };
  }

  return config;
}
