/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, isMappedValueValidForSchema, Schema } from '../../schema.js';
import {
  BalanceStatusEnum,
  balanceStatusEnumSchema,
} from '../balanceStatusEnum.js';

/** This is a container type for any-of types. */
export type Data7BalanceStatus = BalanceStatusEnum;

export const data7BalanceStatusSchema: Schema<Data7BalanceStatus> = anyOf([
  balanceStatusEnumSchema,
]);

export namespace Data7BalanceStatus {
  /**
   * Validation method to narrow down union type to BalanceStatusEnum type case.
   *
   * This is BalanceStatus case.
   */
  export function isBalanceStatusEnum(
    value: unknown
  ): value is BalanceStatusEnum {
    return isMappedValueValidForSchema(value, balanceStatusEnumSchema);
  }
}
