/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, array, Schema, string } from '../../schema.js';

/** This is a container type for any-of types. */
export type Data7RiskStatusReasons = string[];

export const data7RiskStatusReasonsSchema: Schema<Data7RiskStatusReasons> = anyOf(
  [array(string())]
);

export namespace Data7RiskStatusReasons {
  /**
   * Validation method to narrow down union type to string[] type case.
   *
   * This is Array of String case.
   */
  export function isArrayOfString(value: unknown): value is string[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'string')
    );
  }
}
