/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, unknown } from '../../schema.js';

/** This is a container type for any-of types. */
export type Fee1Metadata = unknown;

export const fee1MetadataSchema: Schema<Fee1Metadata> = anyOf([unknown()]);

export namespace Fee1Metadata {
}
