/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, unknown } from '../../schema.js';

/** This is a container type for any-of types. */
export type FeeMetadata = unknown;

export const feeMetadataSchema: Schema<FeeMetadata> = anyOf([unknown()]);

export namespace FeeMetadata {
}
