/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, array, Schema, string } from '../../schema.js';

/** This is a container type for any-of types. */
export type StepStatusReasons = string[];

export const stepStatusReasonsSchema: Schema<StepStatusReasons> = anyOf([
  array(string()),
]);

export namespace StepStatusReasons {
  /**
   * Validation method to narrow down union type to string[] type case.
   *
   * This is Array of String case.
   */
  export function isArrayOfString(value: unknown): value is string[] {
    return (
      Array.isArray(value) && value.every((item) => typeof item === 'string')
    );
  }
}
