/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, string } from '../../schema.js';

/** This is a container type for any-of types. */
export type StepCompletedAt = string;

export const stepCompletedAtSchema: Schema<StepCompletedAt> = anyOf([string()]);

export namespace StepCompletedAt {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is DateTime case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
