/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, isMappedValueValidForSchema, Schema } from '../../schema.js';
import { ProviderKeyEnum, providerKeyEnumSchema } from '../providerKeyEnum.js';

/** This is a container type for any-of types. */
export type TransferStepProviderKey = ProviderKeyEnum;

export const transferStepProviderKeySchema: Schema<TransferStepProviderKey> = anyOf(
  [providerKeyEnumSchema]
);

export namespace TransferStepProviderKey {
  /**
   * Validation method to narrow down union type to ProviderKeyEnum type case.
   *
   * This is ProviderKey case.
   */
  export function isProviderKeyEnum(value: unknown): value is ProviderKeyEnum {
    return isMappedValueValidForSchema(value, providerKeyEnumSchema);
  }
}
