/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { anyOf, Schema, string } from '../../schema.js';

/** This is a container type for any-of types. */
export type UpdateCounterpartyRequestIndividualFirstName = string;

export const updateCounterpartyRequestIndividualFirstNameSchema: Schema<UpdateCounterpartyRequestIndividualFirstName> = anyOf(
  [string()]
);

export namespace UpdateCounterpartyRequestIndividualFirstName {
  /**
   * Validation method to narrow down union type to string type case.
   *
   * This is String case.
   */
  export function isString(value: unknown): value is string {
    return typeof value === 'string';
  }
}
