/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  AccountListResponse,
  accountListResponseSchema,
} from '../models/accountListResponse.js';
import {
  AccountResponse,
  accountResponseSchema,
} from '../models/accountResponse.js';
import {
  CreateBankRequest,
  createBankRequestSchema,
} from '../models/createBankRequest.js';
import {
  CreateBankResponse,
  createBankResponseSchema,
} from '../models/createBankResponse.js';
import {
  CreateWalletRequest,
  createWalletRequestSchema,
} from '../models/createWalletRequest.js';
import {
  CreateWalletResponse,
  createWalletResponseSchema,
} from '../models/createWalletResponse.js';
import { Type4Enum, type4EnumSchema } from '../models/type4Enum.js';
import {
  UpdateAccountRequest,
  updateAccountRequestSchema,
} from '../models/updateAccountRequest.js';
import {
  UpdateAccountResponse,
  updateAccountResponseSchema,
} from '../models/updateAccountResponse.js';
import { boolean, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';

export class AccountsController extends BaseController {
  /**
   * Retrieve all accounts (both bank and wallet accounts) for your workspace.
   *
   * @param authorization     Bearer token for authentication.   To obtain a token, make a request to
   *                                       Auth0:  ```bash curl --request POST \   --url https://dev-awqy75wdabpsnsvu.
   *                                       us.auth0.com/oauth/token \   --header 'content-type: application/json' \   --
   *                                       data '{     "client_id":"YOUR_CLIENT_ID",     "client_secret":
   *                                       "YOUR_CLIENT_SECRET",     "audience":"https://sandbox.tesserx.co",
   *                                       "grant_type":"client_credentials"   }' ```  The response will contain an
   *                                       `access_token` field which should be used as the Bearer token.
   * @param type              Filter by account type
   * @param tenantId          Filter by tenant ID. At most one of tenant_id or counterparty_id may be
   *                                       provided.
   * @param counterpartyId    Filter by counterparty ID. At most one of tenant_id or counterparty_id may
   *                                       be provided.
   * @param includeSensitive  If true, includes sensitive fields like bank_account_number.
   * @return Response from the API call
   */
  async findAll(
    authorization: string,
    type?: Type4Enum,
    tenantId?: string,
    counterpartyId?: string,
    includeSensitive?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountListResponse>> {
    const req = this.createRequest('GET', '/accounts');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      type: [type, optional(type4EnumSchema)],
      tenantId: [tenantId, optional(string())],
      counterpartyId: [counterpartyId, optional(string())],
      includeSensitive: [includeSensitive, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('type', mapped.type);
    req.query('tenant_id', mapped.tenantId);
    req.query('counterparty_id', mapped.counterpartyId);
    req.query('include_sensitive', mapped.includeSensitive);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(accountListResponseSchema, requestOptions);
  }

  /**
   * Create a new fiat bank account.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                  request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                  //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                  'content-type: application/json' \   --data '{     "client_id":
   *                                                  "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                  "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                  "client_credentials"   }' ```  The response will contain an
   *                                                  `access_token` field which should be used as the Bearer token.
   * @param body          Bank account details
   * @return Response from the API call
   */
  async createBank(
    authorization: string,
    body: CreateBankRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateBankResponse>> {
    const req = this.createRequest('POST', '/accounts/banks');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createBankRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createBankResponseSchema, requestOptions);
  }

  /**
   * Create a new stablecoin wallet account.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                    request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                    //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                    'content-type: application/json' \   --data '{     "client_id":
   *                                                    "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                    "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                    "client_credentials"   }' ```  The response will contain an
   *                                                    `access_token` field which should be used as the Bearer token.
   * @param body          Wallet account details
   * @return Response from the API call
   */
  async createWallet(
    authorization: string,
    body: CreateWalletRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateWalletResponse>> {
    const req = this.createRequest('POST', '/accounts/wallets');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createWalletRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createWalletResponseSchema, requestOptions);
  }

  /**
   * Retrieve a specific account (wallet or bank) by its unique identifier
   *
   * @param id                Account ID (UUID)
   * @param authorization     Bearer token for authentication.   To obtain a token, make a request to Auth0:
   *                                     ```bash curl --request POST \   --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                     com/oauth/token \   --header 'content-type: application/json' \   --data '{
   *                                     "client_id":"YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                     "audience":"https://sandbox.tesserx.co",     "grant_type":"client_credentials"
   *                                     }' ```  The response will contain an `access_token` field which should be
   *                                     used as the Bearer token.
   * @param includeSensitive  If true, includes sensitive fields like bank_account_number.
   * @return Response from the API call
   */
  async findOne2(
    id: string,
    authorization: string,
    includeSensitive?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<AccountResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      authorization: [authorization, string()],
      includeSensitive: [includeSensitive, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('include_sensitive', mapped.includeSensitive);
    req.appendTemplatePath`/accounts/${mapped.id}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(accountResponseSchema, requestOptions);
  }

  /**
   * Update an existing account's information.
   *
   * @param id            Account ID (UUID)
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                     request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                     //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                     'content-type: application/json' \   --data '{     "client_id":
   *                                                     "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                     "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                     "client_credentials"   }' ```  The response will contain an
   *                                                     `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async update(
    id: string,
    authorization: string,
    body: UpdateAccountRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateAccountResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      authorization: [authorization, string()],
      body: [body, updateAccountRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/accounts/${mapped.id}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(updateAccountResponseSchema, requestOptions);
  }
}
