/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  Classification7Enum,
  classification7EnumSchema,
} from '../models/classification7Enum.js';
import {
  CounterpartyListResponse,
  counterpartyListResponseSchema,
} from '../models/counterpartyListResponse.js';
import {
  CounterpartyResponse,
  counterpartyResponseSchema,
} from '../models/counterpartyResponse.js';
import {
  CreateCounterpartyRequest,
  createCounterpartyRequestSchema,
} from '../models/createCounterpartyRequest.js';
import {
  CreateCounterpartyResponse,
  createCounterpartyResponseSchema,
} from '../models/createCounterpartyResponse.js';
import {
  UpdateCounterpartyRequest,
  updateCounterpartyRequestSchema,
} from '../models/updateCounterpartyRequest.js';
import {
  UpdateCounterpartyResponse,
  updateCounterpartyResponseSchema,
} from '../models/updateCounterpartyResponse.js';
import { boolean, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';

export class CounterpartiesController extends BaseController {
  /**
   * Create a new counterparty for your workspace.
   *
   * A counterparty is any external party that your organization transacts with,
   * such as vendors, customers, or partners.
   *
   * **Classifications:**
   * - **individual**: A natural person (requires first/last name)
   * - **business**: A legal entity (requires legal name)
   *
   * @param authorization Bearer token for authentication.   To obtain a token,
   *                                                          make a request to Auth0:  ```bash curl --request POST \
   *                                                          --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                                          com/oauth/token \   --header 'content-type:
   *                                                          application/json' \   --data '{     "client_id":
   *                                                          "YOUR_CLIENT_ID",     "client_secret":
   *                                                          "YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                                          tesserx.co",     "grant_type":"client_credentials"   }'
   *                                                          ```  The response will contain an `access_token` field
   *                                                          which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async create(
    authorization: string,
    body: CreateCounterpartyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateCounterpartyResponse>> {
    const req = this.createRequest('POST', '/entities/counterparties');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createCounterpartyRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createCounterpartyResponseSchema, requestOptions);
  }

  /**
   * Retrieve all counterparties for your workspace with optional filtering.
   *
   * Use query parameters to filter results:
   * - **classification**: Filter by 'individual' or 'business'
   *
   * @param authorization  Bearer token for authentication.   To obtain a token, make a request
   *                                              to Auth0:  ```bash curl --request POST \   --url https://dev-
   *                                              awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header 'content-type:
   *                                              application/json' \   --data '{     "client_id":"YOUR_CLIENT_ID",
   *                                              "client_secret":"YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                              tesserx.co",     "grant_type":"client_credentials"   }' ```  The
   *                                              response will contain an `access_token` field which should be used as
   *                                              the Bearer token.
   * @param classification Filter by classification
   * @param includeSecure  Include secure fields (PII)
   * @return Response from the API call
   */
  async findAll1(
    authorization: string,
    classification?: Classification7Enum,
    includeSecure?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CounterpartyListResponse>> {
    const req = this.createRequest('GET', '/entities/counterparties');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      classification: [classification, optional(classification7EnumSchema)],
      includeSecure: [includeSecure, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('classification', mapped.classification);
    req.query('include_secure', mapped.includeSecure);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(counterpartyListResponseSchema, requestOptions);
  }

  /**
   * Retrieve a specific counterparty by its unique identifier
   *
   * @param id             Counterparty ID (UUID)
   * @param authorization  Bearer token for authentication.   To obtain a token, make a request
   *                                              to Auth0:  ```bash curl --request POST \   --url https://dev-
   *                                              awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header 'content-type:
   *                                              application/json' \   --data '{     "client_id":"YOUR_CLIENT_ID",
   *                                              "client_secret":"YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                              tesserx.co",     "grant_type":"client_credentials"   }' ```  The
   *                                              response will contain an `access_token` field which should be used as
   *                                              the Bearer token.
   * @param classification Filter by classification ('individual' or 'business').
   * @param includeSecure  Include secure fields (PII)
   * @return Response from the API call
   */
  async findOne(
    id: string,
    authorization: string,
    classification?: Classification7Enum,
    includeSecure?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CounterpartyResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      authorization: [authorization, string()],
      classification: [classification, optional(classification7EnumSchema)],
      includeSecure: [includeSecure, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('classification', mapped.classification);
    req.query('include_secure', mapped.includeSecure);
    req.appendTemplatePath`/entities/counterparties/${mapped.id}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(counterpartyResponseSchema, requestOptions);
  }

  /**
   * Update an existing counterparty's information.
   *
   * Only provide the fields you want to update. At least one field must be provided.
   *
   * **Note:** If changing classification from 'individual' to 'business' (or vice versa),
   * make sure to also provide the appropriate fields for the new classification.
   *
   * @param id            Counterparty ID (UUID)
   * @param authorization Bearer token for authentication.   To obtain a token,
   *                                                          make a request to Auth0:  ```bash curl --request POST \
   *                                                          --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                                          com/oauth/token \   --header 'content-type:
   *                                                          application/json' \   --data '{     "client_id":
   *                                                          "YOUR_CLIENT_ID",     "client_secret":
   *                                                          "YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                                          tesserx.co",     "grant_type":"client_credentials"   }'
   *                                                          ```  The response will contain an `access_token` field
   *                                                          which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async update1(
    id: string,
    authorization: string,
    body: UpdateCounterpartyRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateCounterpartyResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      authorization: [authorization, string()],
      body: [body, updateCounterpartyRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/entities/counterparties/${mapped.id}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(updateCounterpartyResponseSchema, requestOptions);
  }
}
