/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  ExecutePaymentRequestDto,
  executePaymentRequestDtoSchema,
} from '../models/executePaymentRequestDto.js';
import {
  PaymentResponse,
  paymentResponseSchema,
} from '../models/paymentResponse.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';

export class ExperimentalController extends BaseController {
  /**
   * Accepts a signature for a payment step. Currently echoes the request, structured for future
   * execution logic.
   *
   * @param paymentId     Payment ID to execute.
   * @param stepId        Transfer step ID to execute.
   * @param authorization Bearer token for authentication.   To obtain a token,
   *                                                         make a request to Auth0:  ```bash curl --request POST \   -
   *                                                         -url https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token
   *                                                         \   --header 'content-type: application/json' \   --data
   *                                                         '{     "client_id":"YOUR_CLIENT_ID",     "client_secret":
   *                                                         "YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                                         tesserx.co",     "grant_type":"client_credentials"   }'
   *                                                         ```  The response will contain an `access_token` field
   *                                                         which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async executePayment(
    paymentId: string,
    stepId: string,
    authorization: string,
    body: ExecutePaymentRequestDto,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      paymentId: [paymentId, string()],
      stepId: [stepId, string()],
      authorization: [authorization, string()],
      body: [body, executePaymentRequestDtoSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/payments/${mapped.paymentId}/steps/${mapped.stepId}`;
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }
}
