/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Response, responseSchema } from '../models/response.js';
import { BaseController } from './baseController.js';

export class HealthController extends BaseController {
  /**
   * @return Response from the API call
   */
  async getHealth(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Response>> {
    const req = this.createRequest('GET', '/');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(responseSchema, requestOptions);
  }
}
