/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import { Network, networkSchema } from '../models/network.js';
import { array, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';

export class NetworksController extends BaseController {
  /**
   * Retrieve list of all supported blockchain networks. Returns an array with network key and display
   * name.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a request to Auth0:
   *                                ```bash curl --request POST \   --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                com/oauth/token \   --header 'content-type: application/json' \   --data '{
   *                                "client_id":"YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                "audience":"https://sandbox.tesserx.co",     "grant_type":"client_credentials"   }'
   *                                ```  The response will contain an `access_token` field which should be used as the
   *                                Bearer token.
   * @return Response from the API call
   */
  async getNetworks(
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<Network[]>> {
    const req = this.createRequest('GET', '/networks');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(array(networkSchema), requestOptions);
  }
}
