/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreatePaymentRequest,
  createPaymentRequestSchema,
} from '../models/createPaymentRequest.js';
import {
  PaymentListResponse,
  paymentListResponseSchema,
} from '../models/paymentListResponse.js';
import {
  PaymentResponse,
  paymentResponseSchema,
} from '../models/paymentResponse.js';
import {
  PaymentType3Enum,
  paymentType3EnumSchema,
} from '../models/paymentType3Enum.js';
import {
  ReviewPaymentRequest,
  reviewPaymentRequestSchema,
} from '../models/reviewPaymentRequest.js';
import {
  UpdatePaymentRequest,
  updatePaymentRequestSchema,
} from '../models/updatePaymentRequest.js';
import { number, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';

export class PaymentsController extends BaseController {
  /**
   * Retrieve all payments for the authenticated user's organization.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a request to
   *                                          Auth0:  ```bash curl --request POST \   --url https://dev-
   *                                          awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header 'content-type:
   *                                          application/json' \   --data '{     "client_id":"YOUR_CLIENT_ID",
   *                                          "client_secret":"YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                          tesserx.co",     "grant_type":"client_credentials"   }' ```  The response
   *                                          will contain an `access_token` field which should be used as the Bearer
   *                                          token.
   * @param startDate     Filter payments created on or after this ISO 8601 date.
   * @param endDate       Filter payments created before this ISO 8601 date.
   * @param paymentType   Filter payments by type ('withdrawal', 'deposit', 'onramp', 'offramp',
   *                                          'payment', 'transfer').
   * @param page          Page number for pagination (1-based).
   * @param limit         Number of items per page.
   * @return Response from the API call
   */
  async getPayments(
    authorization: string,
    startDate?: string,
    endDate?: string,
    paymentType?: PaymentType3Enum,
    page?: number,
    limit?: number,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentListResponse>> {
    const req = this.createRequest('GET', '/payments');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      startDate: [startDate, optional(string())],
      endDate: [endDate, optional(string())],
      paymentType: [paymentType, optional(paymentType3EnumSchema)],
      page: [page, optional(number())],
      limit: [limit, optional(number())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('start_date', mapped.startDate);
    req.query('end_date', mapped.endDate);
    req.query('payment_type', mapped.paymentType);
    req.query('page', mapped.page);
    req.query('limit', mapped.limit);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentListResponseSchema, requestOptions);
  }

  /**
   * Create a payment. Returns the created payment details.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                     request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                     //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                     'content-type: application/json' \   --data '{     "client_id":
   *                                                     "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                     "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                     "client_credentials"   }' ```  The response will contain an
   *                                                     `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async createPayment(
    authorization: string,
    body: CreatePaymentRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('POST', '/payments');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createPaymentRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }

  /**
   * Retrieve a specific payment by ID.
   *
   * @param paymentId
   * @param authorization Bearer token for authentication.   To obtain a token, make a request to Auth0:
   *                                ```bash curl --request POST \   --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                com/oauth/token \   --header 'content-type: application/json' \   --data '{
   *                                "client_id":"YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                "audience":"https://sandbox.tesserx.co",     "grant_type":"client_credentials"   }'
   *                                ```  The response will contain an `access_token` field which should be used as the
   *                                Bearer token.
   * @return Response from the API call
   */
  async getPaymentById(
    paymentId: string,
    authorization: string,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      paymentId: [paymentId, string()],
      authorization: [authorization, string()],
    });
    req.header('Authorization', mapped.authorization);
    req.appendTemplatePath`/payments/${mapped.paymentId}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }

  /**
   * Update a payment with accounts.
   *
   * @param paymentId
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                     request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                     //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                     'content-type: application/json' \   --data '{     "client_id":
   *                                                     "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                     "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                     "client_credentials"   }' ```  The response will contain an
   *                                                     `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async updatePayment(
    paymentId: string,
    authorization: string,
    body: UpdatePaymentRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      paymentId: [paymentId, string()],
      authorization: [authorization, string()],
      body: [body, updatePaymentRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/payments/${mapped.paymentId}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }

  /**
   * Manually review and approve or reject a payment requiring risk review.
   *
   * @param paymentId     Unique identifier of the payment to review
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                     request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                     //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                     'content-type: application/json' \   --data '{     "client_id":
   *                                                     "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                     "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                     "client_credentials"   }' ```  The response will contain an
   *                                                     `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async reviewPayment(
    paymentId: string,
    authorization: string,
    body: ReviewPaymentRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('POST');
    const mapped = req.prepareArgs({
      paymentId: [paymentId, string()],
      authorization: [authorization, string()],
      body: [body, reviewPaymentRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/payments/${mapped.paymentId}/review`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }
}
