/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateTenantRequest,
  createTenantRequestSchema,
} from '../models/createTenantRequest.js';
import {
  CreateTenantResponse,
  createTenantResponseSchema,
} from '../models/createTenantResponse.js';
import {
  TenantListResponse,
  tenantListResponseSchema,
} from '../models/tenantListResponse.js';
import {
  TenantResponse,
  tenantResponseSchema,
} from '../models/tenantResponse.js';
import {
  UpdateTenantRequest,
  updateTenantRequestSchema,
} from '../models/updateTenantRequest.js';
import {
  UpdateTenantResponse,
  updateTenantResponseSchema,
} from '../models/updateTenantResponse.js';
import { boolean, optional, string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';

export class TenantsController extends BaseController {
  /**
   * Create a new tenant for your workspace. Tenants are business customers that integrate via APIs.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                    request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                    //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                    'content-type: application/json' \   --data '{     "client_id":
   *                                                    "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                    "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                    "client_credentials"   }' ```  The response will contain an
   *                                                    `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async create1(
    authorization: string,
    body: CreateTenantRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<CreateTenantResponse>> {
    const req = this.createRequest('POST', '/entities/tenants');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createTenantRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(createTenantResponseSchema, requestOptions);
  }

  /**
   * Retrieve all tenants for your workspace with optional search filtering.
   *
   * @param authorization  Bearer token for authentication.   To obtain a token, make a request to Auth0:
   *                                  ```bash curl --request POST \   --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                  com/oauth/token \   --header 'content-type: application/json' \   --data '{
   *                                  "client_id":"YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                  "audience":"https://sandbox.tesserx.co",     "grant_type":"client_credentials"
   *                                  }' ```  The response will contain an `access_token` field which should be used as
   *                                  the Bearer token.
   * @param includeSecure  Include secure fields (PII)
   * @return Response from the API call
   */
  async findAll2(
    authorization: string,
    includeSecure?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TenantListResponse>> {
    const req = this.createRequest('GET', '/entities/tenants');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      includeSecure: [includeSecure, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('include_secure', mapped.includeSecure);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(tenantListResponseSchema, requestOptions);
  }

  /**
   * Retrieve a specific tenant by its unique identifier
   *
   * @param id             Tenant ID (UUID)
   * @param authorization  Bearer token for authentication.   To obtain a token, make a request to Auth0:
   *                                  ```bash curl --request POST \   --url https://dev-awqy75wdabpsnsvu.us.auth0.
   *                                  com/oauth/token \   --header 'content-type: application/json' \   --data '{
   *                                  "client_id":"YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                  "audience":"https://sandbox.tesserx.co",     "grant_type":"client_credentials"
   *                                  }' ```  The response will contain an `access_token` field which should be used as
   *                                  the Bearer token.
   * @param includeSecure  Include secure fields (PII)
   * @return Response from the API call
   */
  async findOne1(
    id: string,
    authorization: string,
    includeSecure?: boolean,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<TenantResponse>> {
    const req = this.createRequest('GET');
    const mapped = req.prepareArgs({
      id: [id, string()],
      authorization: [authorization, string()],
      includeSecure: [includeSecure, optional(boolean())],
    });
    req.header('Authorization', mapped.authorization);
    req.query('include_secure', mapped.includeSecure);
    req.appendTemplatePath`/entities/tenants/${mapped.id}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(tenantResponseSchema, requestOptions);
  }

  /**
   * Update an existing tenant's information.
   *
   * Only the following fields can be updated:
   * - business_legal_name
   * - business_dba
   * - business_address_country
   * - webhook_url
   *
   * At least one field must be provided.
   *
   * @param id            Tenant ID (UUID)
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                    request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                    //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                    'content-type: application/json' \   --data '{     "client_id":
   *                                                    "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                    "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                    "client_credentials"   }' ```  The response will contain an
   *                                                    `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async update2(
    id: string,
    authorization: string,
    body: UpdateTenantRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<UpdateTenantResponse>> {
    const req = this.createRequest('PATCH');
    const mapped = req.prepareArgs({
      id: [id, string()],
      authorization: [authorization, string()],
      body: [body, updateTenantRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.appendTemplatePath`/entities/tenants/${mapped.id}`;
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(updateTenantResponseSchema, requestOptions);
  }
}
