/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core.js';
import {
  CreateDepositRequest,
  createDepositRequestSchema,
} from '../models/createDepositRequest.js';
import {
  CreateWithdrawalRequest,
  createWithdrawalRequestSchema,
} from '../models/createWithdrawalRequest.js';
import {
  PaymentResponse,
  paymentResponseSchema,
} from '../models/paymentResponse.js';
import { string } from '../schema.js';
import { BaseController } from './baseController.js';
import { ApiError } from '@apimatic/core';

export class TreasuryController extends BaseController {
  /**
   * Create a deposit payment.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make a
   *                                                     request to Auth0:  ```bash curl --request POST \   --url https:
   *                                                     //dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --header
   *                                                     'content-type: application/json' \   --data '{     "client_id":
   *                                                     "YOUR_CLIENT_ID",     "client_secret":"YOUR_CLIENT_SECRET",
   *                                                     "audience":"https://sandbox.tesserx.co",     "grant_type":
   *                                                     "client_credentials"   }' ```  The response will contain an
   *                                                     `access_token` field which should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async createDeposit(
    authorization: string,
    body: CreateDepositRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('POST', '/treasury/deposit');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createDepositRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }

  /**
   * Create a withdrawal payment.
   *
   * @param authorization Bearer token for authentication.   To obtain a token, make
   *                                                        a request to Auth0:  ```bash curl --request POST \   --url
   *                                                        https://dev-awqy75wdabpsnsvu.us.auth0.com/oauth/token \   --
   *                                                        header 'content-type: application/json' \   --data '{
   *                                                        "client_id":"YOUR_CLIENT_ID",     "client_secret":
   *                                                        "YOUR_CLIENT_SECRET",     "audience":"https://sandbox.
   *                                                        tesserx.co",     "grant_type":"client_credentials"   }' ```
   *                                                        The response will contain an `access_token` field which
   *                                                        should be used as the Bearer token.
   * @param body
   * @return Response from the API call
   */
  async createWithdrawal(
    authorization: string,
    body: CreateWithdrawalRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<PaymentResponse>> {
    const req = this.createRequest('POST', '/treasury/withdrawal');
    const mapped = req.prepareArgs({
      authorization: [authorization, string()],
      body: [body, createWithdrawalRequestSchema],
    });
    req.header('Authorization', mapped.authorization);
    req.header('Content-Type', 'application/json');
    req.json(mapped.body);
    req.throwOn(400, ApiError, 'Details coming soon');
    req.authenticate([{ bearer: true }]);
    return req.callAsJson(paymentResponseSchema, requestOptions);
  }
}
