/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { AccountListItem, accountListItemSchema } from './accountListItem.js';

export interface AccountListResponse {
  data: AccountListItem[];
}

export const accountListResponseSchema: Schema<AccountListResponse> = lazy(() =>
  object({ data: ['data', array(accountListItemSchema)] })
);
