/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Account, accountSchema } from './account.js';

export interface AccountResponse {
  data: Account;
}

export const accountResponseSchema: Schema<AccountResponse> = lazy(() =>
  object({ data: ['data', accountSchema] })
);
