/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountListItemBankAccountNumber,
  accountListItemBankAccountNumberSchema,
} from './containers/accountListItemBankAccountNumber.js';
import {
  AccountListItemBankCodeType,
  accountListItemBankCodeTypeSchema,
} from './containers/accountListItemBankCodeType.js';
import {
  AccountListItemBankIdentifierCode,
  accountListItemBankIdentifierCodeSchema,
} from './containers/accountListItemBankIdentifierCode.js';
import {
  AccountListItemBankName,
  accountListItemBankNameSchema,
} from './containers/accountListItemBankName.js';
import {
  AccountListItemCounterpartyId,
  accountListItemCounterpartyIdSchema,
} from './containers/accountListItemCounterpartyId.js';
import {
  AccountListItemCryptoWalletAddress,
  accountListItemCryptoWalletAddressSchema,
} from './containers/accountListItemCryptoWalletAddress.js';
import {
  AccountListItemTenantId,
  accountListItemTenantIdSchema,
} from './containers/accountListItemTenantId.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

export interface AccountListItem {
  /** Unique identifier for the account. */
  id: string;
  /** ID of the workspace. */
  workspaceId?: string;
  /** Tenant ID (optional - if provided, this account is associated with a tenant). At most one of tenant_id or counterparty_id may be set. */
  tenantId?: AccountListItemTenantId;
  /** Counterparty ID (optional - if provided, this account is associated with a counterparty). At most one of tenant_id or counterparty_id may be set. */
  counterpartyId?: AccountListItemCounterpartyId;
  /** Account type. */
  type: TypeEnum;
  /** Account name. */
  name: string;
  /** Bank name (for fiat accounts). */
  bankName?: AccountListItemBankName;
  /** Bank code type (e.g., SWIFT, BIC). */
  bankCodeType?: AccountListItemBankCodeType;
  /** Bank identifier code value. */
  bankIdentifierCode?: AccountListItemBankIdentifierCode;
  /** Crypto wallet address (for wallet accounts). */
  cryptoWalletAddress?: AccountListItemCryptoWalletAddress;
  /** Bank account number (IBAN, etc). Only returned if include_sensitive=true. */
  bankAccountNumber?: AccountListItemBankAccountNumber;
  /** Creation timestamp. */
  createdAt: string;
  /** Last update timestamp. */
  updatedAt: string;
}

export const accountListItemSchema: Schema<AccountListItem> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', optional(string())],
    tenantId: ['tenant_id', optional(accountListItemTenantIdSchema)],
    counterpartyId: [
      'counterparty_id',
      optional(accountListItemCounterpartyIdSchema),
    ],
    type: ['type', typeEnumSchema],
    name: ['name', string()],
    bankName: ['bank_name', optional(accountListItemBankNameSchema)],
    bankCodeType: [
      'bank_code_type',
      optional(accountListItemBankCodeTypeSchema),
    ],
    bankIdentifierCode: [
      'bank_identifier_code',
      optional(accountListItemBankIdentifierCodeSchema),
    ],
    cryptoWalletAddress: [
      'crypto_wallet_address',
      optional(accountListItemCryptoWalletAddressSchema),
    ],
    bankAccountNumber: [
      'bank_account_number',
      optional(accountListItemBankAccountNumberSchema),
    ],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
