/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountSafeBankCodeType,
  accountSafeBankCodeTypeSchema,
} from './containers/accountSafeBankCodeType.js';
import {
  AccountSafeBankIdentifierCode,
  accountSafeBankIdentifierCodeSchema,
} from './containers/accountSafeBankIdentifierCode.js';
import {
  AccountSafeBankName,
  accountSafeBankNameSchema,
} from './containers/accountSafeBankName.js';
import {
  AccountSafeCounterpartyId,
  accountSafeCounterpartyIdSchema,
} from './containers/accountSafeCounterpartyId.js';
import {
  AccountSafeCryptoWalletAddress,
  accountSafeCryptoWalletAddressSchema,
} from './containers/accountSafeCryptoWalletAddress.js';
import {
  AccountSafeTenantId,
  accountSafeTenantIdSchema,
} from './containers/accountSafeTenantId.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

export interface AccountSafe {
  /** Unique identifier for the account. */
  id: string;
  /** ID of the workspace. */
  workspaceId?: string;
  /** Tenant ID (optional - if provided, this account is associated with a tenant). At most one of tenant_id or counterparty_id may be set. */
  tenantId?: AccountSafeTenantId;
  /** Counterparty ID (optional - if provided, this account is associated with a counterparty). At most one of tenant_id or counterparty_id may be set. */
  counterpartyId?: AccountSafeCounterpartyId;
  /** Account type. */
  type: TypeEnum;
  /** Account name. */
  name: string;
  /** Bank name (for fiat accounts). */
  bankName?: AccountSafeBankName;
  /** Bank code type (e.g., SWIFT, BIC). */
  bankCodeType?: AccountSafeBankCodeType;
  /** Bank identifier code value. */
  bankIdentifierCode?: AccountSafeBankIdentifierCode;
  /** Crypto wallet address (for wallet accounts). */
  cryptoWalletAddress?: AccountSafeCryptoWalletAddress;
  /** Creation timestamp. */
  createdAt: string;
  /** Last update timestamp. */
  updatedAt: string;
}

export const accountSafeSchema: Schema<AccountSafe> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', optional(string())],
    tenantId: ['tenant_id', optional(accountSafeTenantIdSchema)],
    counterpartyId: [
      'counterparty_id',
      optional(accountSafeCounterpartyIdSchema),
    ],
    type: ['type', typeEnumSchema],
    name: ['name', string()],
    bankName: ['bank_name', optional(accountSafeBankNameSchema)],
    bankCodeType: ['bank_code_type', optional(accountSafeBankCodeTypeSchema)],
    bankIdentifierCode: [
      'bank_identifier_code',
      optional(accountSafeBankIdentifierCodeSchema),
    ],
    cryptoWalletAddress: [
      'crypto_wallet_address',
      optional(accountSafeCryptoWalletAddressSchema),
    ],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
