/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  AccountBankAccountNumber,
  accountBankAccountNumberSchema,
} from './containers/accountBankAccountNumber.js';
import {
  AccountBankCodeType,
  accountBankCodeTypeSchema,
} from './containers/accountBankCodeType.js';
import {
  AccountBankIdentifierCode,
  accountBankIdentifierCodeSchema,
} from './containers/accountBankIdentifierCode.js';
import {
  AccountBankName,
  accountBankNameSchema,
} from './containers/accountBankName.js';
import {
  AccountCounterpartyId,
  accountCounterpartyIdSchema,
} from './containers/accountCounterpartyId.js';
import {
  AccountCryptoWalletAddress,
  accountCryptoWalletAddressSchema,
} from './containers/accountCryptoWalletAddress.js';
import {
  AccountTenantId,
  accountTenantIdSchema,
} from './containers/accountTenantId.js';
import { TypeEnum, typeEnumSchema } from './typeEnum.js';

export interface Account {
  /** Unique identifier for the account. */
  id: string;
  /** ID of the workspace. */
  workspaceId?: string;
  /** Tenant ID (optional - if provided, this account is associated with a tenant). At most one of tenant_id or counterparty_id may be set. */
  tenantId?: AccountTenantId;
  /** Counterparty ID (optional - if provided, this account is associated with a counterparty). At most one of tenant_id or counterparty_id may be set. */
  counterpartyId?: AccountCounterpartyId;
  /** Account type. */
  type: TypeEnum;
  /** Account name. */
  name: string;
  /** Bank name (for fiat accounts). */
  bankName?: AccountBankName;
  /** Bank code type (e.g., SWIFT, BIC). */
  bankCodeType?: AccountBankCodeType;
  /** Bank identifier code value. */
  bankIdentifierCode?: AccountBankIdentifierCode;
  /** Crypto wallet address (for wallet accounts). */
  cryptoWalletAddress?: AccountCryptoWalletAddress;
  /** Bank account number (IBAN, etc). Only returned if include_sensitive=true. */
  bankAccountNumber?: AccountBankAccountNumber;
  /** Creation timestamp. */
  createdAt: string;
  /** Last update timestamp. */
  updatedAt: string;
}

export const accountSchema: Schema<Account> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', optional(string())],
    tenantId: ['tenant_id', optional(accountTenantIdSchema)],
    counterpartyId: ['counterparty_id', optional(accountCounterpartyIdSchema)],
    type: ['type', typeEnumSchema],
    name: ['name', string()],
    bankName: ['bank_name', optional(accountBankNameSchema)],
    bankCodeType: ['bank_code_type', optional(accountBankCodeTypeSchema)],
    bankIdentifierCode: [
      'bank_identifier_code',
      optional(accountBankIdentifierCodeSchema),
    ],
    cryptoWalletAddress: [
      'crypto_wallet_address',
      optional(accountCryptoWalletAddressSchema),
    ],
    bankAccountNumber: [
      'bank_account_number',
      optional(accountBankAccountNumberSchema),
    ],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
