/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BalanceStatusEnum
 */
export enum BalanceStatusEnum {
  Unreserved = 'unreserved',
  Reserved = 'reserved',
  InsufficientBalance = 'insufficient_balance',
}

/**
 * Schema for BalanceStatusEnum
 */
export const balanceStatusEnumSchema: Schema<BalanceStatusEnum> = stringEnum(
  BalanceStatusEnum
);
