/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for BalanceStatus1Enum
 */
export enum BalanceStatus1Enum {
  Unreserved = 'unreserved',
  Reserved = 'reserved',
  InsufficientBalance = 'insufficient_balance',
}

/**
 * Schema for BalanceStatus1Enum
 */
export const balanceStatus1EnumSchema: Schema<BalanceStatus1Enum> = stringEnum(
  BalanceStatus1Enum
);
