/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ClassificationEnum
 */
export enum ClassificationEnum {
  Individual = 'individual',
  Business = 'business',
}

/**
 * Schema for ClassificationEnum
 */
export const classificationEnumSchema: Schema<ClassificationEnum> = stringEnum(
  ClassificationEnum
);
