/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Classification7Enum
 */
export enum Classification7Enum {
  Individual = 'individual',
  Business = 'business',
}

/**
 * Schema for Classification7Enum
 */
export const classification7EnumSchema: Schema<Classification7Enum> = stringEnum(
  Classification7Enum
);
