/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Counterparty, counterpartySchema } from './counterparty.js';

export interface CounterpartyListResponse {
  /** List of counterparties */
  data: Counterparty[];
}

export const counterpartyListResponseSchema: Schema<CounterpartyListResponse> = lazy(
  () => object({ data: ['data', array(counterpartySchema)] })
);
