/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  ClassificationEnum,
  classificationEnumSchema,
} from './classificationEnum.js';
import {
  CounterpartyBusinessAddressCountry,
  counterpartyBusinessAddressCountrySchema,
} from './containers/counterpartyBusinessAddressCountry.js';
import {
  CounterpartyBusinessCity,
  counterpartyBusinessCitySchema,
} from './containers/counterpartyBusinessCity.js';
import {
  CounterpartyBusinessDba,
  counterpartyBusinessDbaSchema,
} from './containers/counterpartyBusinessDba.js';
import {
  CounterpartyBusinessLegalEntityIdentifier,
  counterpartyBusinessLegalEntityIdentifierSchema,
} from './containers/counterpartyBusinessLegalEntityIdentifier.js';
import {
  CounterpartyBusinessLegalName,
  counterpartyBusinessLegalNameSchema,
} from './containers/counterpartyBusinessLegalName.js';
import {
  CounterpartyBusinessState,
  counterpartyBusinessStateSchema,
} from './containers/counterpartyBusinessState.js';
import {
  CounterpartyBusinessStreetAddress1,
  counterpartyBusinessStreetAddress1Schema,
} from './containers/counterpartyBusinessStreetAddress1.js';
import {
  CounterpartyBusinessStreetAddress2,
  counterpartyBusinessStreetAddress2Schema,
} from './containers/counterpartyBusinessStreetAddress2.js';
import {
  CounterpartyIndividualAddressCountry,
  counterpartyIndividualAddressCountrySchema,
} from './containers/counterpartyIndividualAddressCountry.js';
import {
  CounterpartyIndividualCity,
  counterpartyIndividualCitySchema,
} from './containers/counterpartyIndividualCity.js';
import {
  CounterpartyIndividualDateOfBirth,
  counterpartyIndividualDateOfBirthSchema,
} from './containers/counterpartyIndividualDateOfBirth.js';
import {
  CounterpartyIndividualFirstName,
  counterpartyIndividualFirstNameSchema,
} from './containers/counterpartyIndividualFirstName.js';
import {
  CounterpartyIndividualLastName,
  counterpartyIndividualLastNameSchema,
} from './containers/counterpartyIndividualLastName.js';
import {
  CounterpartyIndividualNationalIdentificationNumber,
  counterpartyIndividualNationalIdentificationNumberSchema,
} from './containers/counterpartyIndividualNationalIdentificationNumber.js';
import {
  CounterpartyIndividualPostalCode,
  counterpartyIndividualPostalCodeSchema,
} from './containers/counterpartyIndividualPostalCode.js';
import {
  CounterpartyIndividualState,
  counterpartyIndividualStateSchema,
} from './containers/counterpartyIndividualState.js';
import {
  CounterpartyIndividualStreetAddress1,
  counterpartyIndividualStreetAddress1Schema,
} from './containers/counterpartyIndividualStreetAddress1.js';
import {
  CounterpartyIndividualStreetAddress2,
  counterpartyIndividualStreetAddress2Schema,
} from './containers/counterpartyIndividualStreetAddress2.js';
import {
  CounterpartyTenantId,
  counterpartyTenantIdSchema,
} from './containers/counterpartyTenantId.js';
import { Data, dataSchema } from './data.js';

export interface Counterparty {
  /** Unique identifier for the counterparty. */
  id: string;
  /** Workspace this counterparty belongs to. */
  workspaceId: string;
  /** Classification: 'individual' or 'business'. */
  classification: ClassificationEnum;
  /** Optional reference to a tenant entity. */
  tenantId?: CounterpartyTenantId;
  /** First name (for individuals). Secure field, returned based on include_secure. */
  individualFirstName?: CounterpartyIndividualFirstName;
  /** Last name (for individuals). Secure field, returned based on include_secure. */
  individualLastName?: CounterpartyIndividualLastName;
  /** Country code (for individuals). */
  individualAddressCountry?: CounterpartyIndividualAddressCountry;
  /** Date of birth (for individuals). Secure field, returned based on include_secure. */
  individualDateOfBirth?: CounterpartyIndividualDateOfBirth;
  /** National identification number (for individuals). Secure field, returned based on include_secure. */
  individualNationalIdentificationNumber?: CounterpartyIndividualNationalIdentificationNumber;
  /** Street address line 1 (for individuals). Secure field, returned based on include_secure. */
  individualStreetAddress1?: CounterpartyIndividualStreetAddress1;
  /** Street address line 2 (for individuals). Secure field, returned based on include_secure. */
  individualStreetAddress2?: CounterpartyIndividualStreetAddress2;
  /** City (for individuals). Secure field, returned based on include_secure. */
  individualCity?: CounterpartyIndividualCity;
  /** State/region (for individuals). Secure field, returned based on include_secure. */
  individualState?: CounterpartyIndividualState;
  /** Postal code (for individuals). Secure field, returned based on include_secure. */
  individualPostalCode?: CounterpartyIndividualPostalCode;
  /** Legal business name (for businesses). */
  businessLegalName?: CounterpartyBusinessLegalName;
  /** DBA - Doing Business As name (for businesses). */
  businessDba?: CounterpartyBusinessDba;
  /** Country code (for businesses). */
  businessAddressCountry?: CounterpartyBusinessAddressCountry;
  /** Street address line 1 (for businesses). Secure field, returned based on include_secure. */
  businessStreetAddress1?: CounterpartyBusinessStreetAddress1;
  /** Street address line 2 (for businesses). Secure field, returned based on include_secure. */
  businessStreetAddress2?: CounterpartyBusinessStreetAddress2;
  /** City (for businesses). Secure field, returned based on include_secure. */
  businessCity?: CounterpartyBusinessCity;
  /** State/region (for businesses). Secure field, returned based on include_secure. */
  businessState?: CounterpartyBusinessState;
  /** Legal Entity Identifier (for businesses). Secure field, returned based on include_secure. */
  businessLegalEntityIdentifier?: CounterpartyBusinessLegalEntityIdentifier;
  /** Creation timestamp in ISO 8601 format. */
  createdAt: string;
  /** Last update timestamp in ISO 8601 format. */
  updatedAt: string;
}

export namespace Counterparty {
  /**
   * Validation method to check if the given Counterparty instance is also a
   * Data.
   */
  export function isData(value: Counterparty): value is Data {
    return isMappedValueValidForSchema(value, dataSchema);
  }
}

export const counterpartySchema: Schema<Counterparty> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    classification: ['classification', classificationEnumSchema],
    tenantId: ['tenant_id', optional(counterpartyTenantIdSchema)],
    individualFirstName: [
      'individual_first_name',
      optional(counterpartyIndividualFirstNameSchema),
    ],
    individualLastName: [
      'individual_last_name',
      optional(counterpartyIndividualLastNameSchema),
    ],
    individualAddressCountry: [
      'individual_address_country',
      optional(counterpartyIndividualAddressCountrySchema),
    ],
    individualDateOfBirth: [
      'individual_date_of_birth',
      optional(counterpartyIndividualDateOfBirthSchema),
    ],
    individualNationalIdentificationNumber: [
      'individual_national_identification_number',
      optional(counterpartyIndividualNationalIdentificationNumberSchema),
    ],
    individualStreetAddress1: [
      'individual_street_address1',
      optional(counterpartyIndividualStreetAddress1Schema),
    ],
    individualStreetAddress2: [
      'individual_street_address2',
      optional(counterpartyIndividualStreetAddress2Schema),
    ],
    individualCity: [
      'individual_city',
      optional(counterpartyIndividualCitySchema),
    ],
    individualState: [
      'individual_state',
      optional(counterpartyIndividualStateSchema),
    ],
    individualPostalCode: [
      'individual_postal_code',
      optional(counterpartyIndividualPostalCodeSchema),
    ],
    businessLegalName: [
      'business_legal_name',
      optional(counterpartyBusinessLegalNameSchema),
    ],
    businessDba: ['business_dba', optional(counterpartyBusinessDbaSchema)],
    businessAddressCountry: [
      'business_address_country',
      optional(counterpartyBusinessAddressCountrySchema),
    ],
    businessStreetAddress1: [
      'business_street_address1',
      optional(counterpartyBusinessStreetAddress1Schema),
    ],
    businessStreetAddress2: [
      'business_street_address2',
      optional(counterpartyBusinessStreetAddress2Schema),
    ],
    businessCity: ['business_city', optional(counterpartyBusinessCitySchema)],
    businessState: [
      'business_state',
      optional(counterpartyBusinessStateSchema),
    ],
    businessLegalEntityIdentifier: [
      'business_legal_entity_identifier',
      optional(counterpartyBusinessLegalEntityIdentifierSchema),
    ],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
