/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CreatePaymentRequest {
  /** Source currency code (e.g., 'USDC'). See GET /currencies for supported values. */
  fromCurrency: string;
  /** Destination currency code (e.g., 'USD'). See GET /currencies for supported values. */
  toCurrency: string;
  /** Amount to send in source currency units. Required if to_amount is not provided. */
  fromAmount?: string;
  /** Amount to receive in destination currency units. Required if from_amount is not provided. */
  toAmount?: string;
  /** Blockchain network for source currency (e.g., 'POLYGON'). See GET /networks for supported values. */
  fromNetwork?: string;
  /** Blockchain network for destination currency (if applicable). See GET /networks for supported values. */
  toNetwork?: string;
  /** Optional external reference ID for the organization. */
  organizationReferenceId?: string;
  /** ID of the account originating the payment. */
  originatorAccountId?: string;
  /** ID of the source account (e.g., wallet). */
  sourceAccountId?: string;
  /** ID of the beneficiary account. */
  beneficiaryAccountId?: string;
}

export const createPaymentRequestSchema: Schema<CreatePaymentRequest> = object({
  fromCurrency: ['from_currency', string()],
  toCurrency: ['to_currency', string()],
  fromAmount: ['from_amount', optional(string())],
  toAmount: ['to_amount', optional(string())],
  fromNetwork: ['from_network', optional(string())],
  toNetwork: ['to_network', optional(string())],
  organizationReferenceId: ['organization_reference_id', optional(string())],
  originatorAccountId: ['originator_account_id', optional(string())],
  sourceAccountId: ['source_account_id', optional(string())],
  beneficiaryAccountId: ['beneficiary_account_id', optional(string())],
});
