/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CreateDepositRequest {
  /** Source currency code. */
  fromCurrency: string;
  /** Destination currency code. */
  toCurrency: string;
  /** Amount to send. Required if to_amount is missing. */
  fromAmount?: string;
  /** Amount to receive. Required if from_amount is missing. */
  toAmount?: string;
  /** Optional tenant ID. */
  tenantId?: string;
  /** Destination account ID. */
  toAccountId: string;
  /** Network for the deposit. */
  toNetwork: string;
}

export const createDepositRequestSchema: Schema<CreateDepositRequest> = object({
  fromCurrency: ['from_currency', string()],
  toCurrency: ['to_currency', string()],
  fromAmount: ['from_amount', optional(string())],
  toAmount: ['to_amount', optional(string())],
  tenantId: ['tenant_id', optional(string())],
  toAccountId: ['to_account_id', string()],
  toNetwork: ['to_network', string()],
});
