/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  ClassificationEnum,
  classificationEnumSchema,
} from './classificationEnum.js';
import {
  CreateCounterpartyRequestBusinessAddressCountry,
  createCounterpartyRequestBusinessAddressCountrySchema,
} from './containers/createCounterpartyRequestBusinessAddressCountry.js';
import {
  CreateCounterpartyRequestBusinessCity,
  createCounterpartyRequestBusinessCitySchema,
} from './containers/createCounterpartyRequestBusinessCity.js';
import {
  CreateCounterpartyRequestBusinessDba,
  createCounterpartyRequestBusinessDbaSchema,
} from './containers/createCounterpartyRequestBusinessDba.js';
import {
  CreateCounterpartyRequestBusinessLegalEntityIdentifier,
  createCounterpartyRequestBusinessLegalEntityIdentifierSchema,
} from './containers/createCounterpartyRequestBusinessLegalEntityIdentifier.js';
import {
  CreateCounterpartyRequestBusinessLegalName,
  createCounterpartyRequestBusinessLegalNameSchema,
} from './containers/createCounterpartyRequestBusinessLegalName.js';
import {
  CreateCounterpartyRequestBusinessState,
  createCounterpartyRequestBusinessStateSchema,
} from './containers/createCounterpartyRequestBusinessState.js';
import {
  CreateCounterpartyRequestBusinessStreetAddress1,
  createCounterpartyRequestBusinessStreetAddress1Schema,
} from './containers/createCounterpartyRequestBusinessStreetAddress1.js';
import {
  CreateCounterpartyRequestBusinessStreetAddress2,
  createCounterpartyRequestBusinessStreetAddress2Schema,
} from './containers/createCounterpartyRequestBusinessStreetAddress2.js';
import {
  CreateCounterpartyRequestIndividualAddressCountry,
  createCounterpartyRequestIndividualAddressCountrySchema,
} from './containers/createCounterpartyRequestIndividualAddressCountry.js';
import {
  CreateCounterpartyRequestIndividualCity,
  createCounterpartyRequestIndividualCitySchema,
} from './containers/createCounterpartyRequestIndividualCity.js';
import {
  CreateCounterpartyRequestIndividualDateOfBirth,
  createCounterpartyRequestIndividualDateOfBirthSchema,
} from './containers/createCounterpartyRequestIndividualDateOfBirth.js';
import {
  CreateCounterpartyRequestIndividualFirstName,
  createCounterpartyRequestIndividualFirstNameSchema,
} from './containers/createCounterpartyRequestIndividualFirstName.js';
import {
  CreateCounterpartyRequestIndividualLastName,
  createCounterpartyRequestIndividualLastNameSchema,
} from './containers/createCounterpartyRequestIndividualLastName.js';
import {
  CreateCounterpartyRequestIndividualNationalIdentificationNumber,
  createCounterpartyRequestIndividualNationalIdentificationNumberSchema,
} from './containers/createCounterpartyRequestIndividualNationalIdentificationNumber.js';
import {
  CreateCounterpartyRequestIndividualPostalCode,
  createCounterpartyRequestIndividualPostalCodeSchema,
} from './containers/createCounterpartyRequestIndividualPostalCode.js';
import {
  CreateCounterpartyRequestIndividualState,
  createCounterpartyRequestIndividualStateSchema,
} from './containers/createCounterpartyRequestIndividualState.js';
import {
  CreateCounterpartyRequestIndividualStreetAddress1,
  createCounterpartyRequestIndividualStreetAddress1Schema,
} from './containers/createCounterpartyRequestIndividualStreetAddress1.js';
import {
  CreateCounterpartyRequestIndividualStreetAddress2,
  createCounterpartyRequestIndividualStreetAddress2Schema,
} from './containers/createCounterpartyRequestIndividualStreetAddress2.js';
import {
  CreateCounterpartyRequestTenantId,
  createCounterpartyRequestTenantIdSchema,
} from './containers/createCounterpartyRequestTenantId.js';

export interface CreateCounterpartyRequest {
  /** Classification: 'individual' or 'business'. */
  classification: ClassificationEnum;
  /** ID of the tenant entity (optional). */
  tenantId?: CreateCounterpartyRequestTenantId;
  /** First name (required if classification is 'individual'). Secure field, returned based on include_secure. */
  individualFirstName?: CreateCounterpartyRequestIndividualFirstName;
  /** Last name (required if classification is 'individual'). Secure field, returned based on include_secure. */
  individualLastName?: CreateCounterpartyRequestIndividualLastName;
  /** ISO 3166-1 alpha-2 or alpha-3 country code. */
  individualAddressCountry?: CreateCounterpartyRequestIndividualAddressCountry;
  /** Date of birth (for individuals). */
  individualDateOfBirth?: CreateCounterpartyRequestIndividualDateOfBirth;
  /** National identification number (for individuals). Secure field, returned based on include_secure. */
  individualNationalIdentificationNumber?: CreateCounterpartyRequestIndividualNationalIdentificationNumber;
  /** Street address line 1 (for individuals). Secure field, returned based on include_secure. */
  individualStreetAddress1?: CreateCounterpartyRequestIndividualStreetAddress1;
  /** Street address line 2 (for individuals). Secure field, returned based on include_secure. */
  individualStreetAddress2?: CreateCounterpartyRequestIndividualStreetAddress2;
  /** City (for individuals). Secure field, returned based on include_secure. */
  individualCity?: CreateCounterpartyRequestIndividualCity;
  /** State/region (for individuals). Secure field, returned based on include_secure. */
  individualState?: CreateCounterpartyRequestIndividualState;
  /** Postal code (for individuals). Secure field, returned based on include_secure. */
  individualPostalCode?: CreateCounterpartyRequestIndividualPostalCode;
  /** Legal business name (required if classification is 'business'). */
  businessLegalName?: CreateCounterpartyRequestBusinessLegalName;
  /** Doing Business As name (optional). */
  businessDba?: CreateCounterpartyRequestBusinessDba;
  /** ISO 3166-1 alpha-2 or alpha-3 country code. */
  businessAddressCountry?: CreateCounterpartyRequestBusinessAddressCountry;
  /** Street address line 1 (for businesses). */
  businessStreetAddress1?: CreateCounterpartyRequestBusinessStreetAddress1;
  /** Street address line 2 (for businesses). */
  businessStreetAddress2?: CreateCounterpartyRequestBusinessStreetAddress2;
  /** City (for businesses). */
  businessCity?: CreateCounterpartyRequestBusinessCity;
  /** State/region (for businesses). */
  businessState?: CreateCounterpartyRequestBusinessState;
  /** Legal Entity Identifier (for businesses). Secure field, returned based on include_secure. */
  businessLegalEntityIdentifier?: CreateCounterpartyRequestBusinessLegalEntityIdentifier;
}

export const createCounterpartyRequestSchema: Schema<CreateCounterpartyRequest> = lazy(
  () =>
    object({
      classification: ['classification', classificationEnumSchema],
      tenantId: [
        'tenant_id',
        optional(createCounterpartyRequestTenantIdSchema),
      ],
      individualFirstName: [
        'individual_first_name',
        optional(createCounterpartyRequestIndividualFirstNameSchema),
      ],
      individualLastName: [
        'individual_last_name',
        optional(createCounterpartyRequestIndividualLastNameSchema),
      ],
      individualAddressCountry: [
        'individual_address_country',
        optional(createCounterpartyRequestIndividualAddressCountrySchema),
      ],
      individualDateOfBirth: [
        'individual_date_of_birth',
        optional(createCounterpartyRequestIndividualDateOfBirthSchema),
      ],
      individualNationalIdentificationNumber: [
        'individual_national_identification_number',
        optional(
          createCounterpartyRequestIndividualNationalIdentificationNumberSchema
        ),
      ],
      individualStreetAddress1: [
        'individual_street_address1',
        optional(createCounterpartyRequestIndividualStreetAddress1Schema),
      ],
      individualStreetAddress2: [
        'individual_street_address2',
        optional(createCounterpartyRequestIndividualStreetAddress2Schema),
      ],
      individualCity: [
        'individual_city',
        optional(createCounterpartyRequestIndividualCitySchema),
      ],
      individualState: [
        'individual_state',
        optional(createCounterpartyRequestIndividualStateSchema),
      ],
      individualPostalCode: [
        'individual_postal_code',
        optional(createCounterpartyRequestIndividualPostalCodeSchema),
      ],
      businessLegalName: [
        'business_legal_name',
        optional(createCounterpartyRequestBusinessLegalNameSchema),
      ],
      businessDba: [
        'business_dba',
        optional(createCounterpartyRequestBusinessDbaSchema),
      ],
      businessAddressCountry: [
        'business_address_country',
        optional(createCounterpartyRequestBusinessAddressCountrySchema),
      ],
      businessStreetAddress1: [
        'business_street_address1',
        optional(createCounterpartyRequestBusinessStreetAddress1Schema),
      ],
      businessStreetAddress2: [
        'business_street_address2',
        optional(createCounterpartyRequestBusinessStreetAddress2Schema),
      ],
      businessCity: [
        'business_city',
        optional(createCounterpartyRequestBusinessCitySchema),
      ],
      businessState: [
        'business_state',
        optional(createCounterpartyRequestBusinessStateSchema),
      ],
      businessLegalEntityIdentifier: [
        'business_legal_entity_identifier',
        optional(createCounterpartyRequestBusinessLegalEntityIdentifierSchema),
      ],
    })
);
