/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  CreateTenantRequestBusinessAddressCountry,
  createTenantRequestBusinessAddressCountrySchema,
} from './containers/createTenantRequestBusinessAddressCountry.js';
import {
  CreateTenantRequestBusinessCity,
  createTenantRequestBusinessCitySchema,
} from './containers/createTenantRequestBusinessCity.js';
import {
  CreateTenantRequestBusinessDba,
  createTenantRequestBusinessDbaSchema,
} from './containers/createTenantRequestBusinessDba.js';
import {
  CreateTenantRequestBusinessLegalEntityIdentifier,
  createTenantRequestBusinessLegalEntityIdentifierSchema,
} from './containers/createTenantRequestBusinessLegalEntityIdentifier.js';
import {
  CreateTenantRequestBusinessState,
  createTenantRequestBusinessStateSchema,
} from './containers/createTenantRequestBusinessState.js';
import {
  CreateTenantRequestBusinessStreetAddress1,
  createTenantRequestBusinessStreetAddress1Schema,
} from './containers/createTenantRequestBusinessStreetAddress1.js';
import {
  CreateTenantRequestBusinessStreetAddress2,
  createTenantRequestBusinessStreetAddress2Schema,
} from './containers/createTenantRequestBusinessStreetAddress2.js';
import {
  CreateTenantRequestWebhookUrl,
  createTenantRequestWebhookUrlSchema,
} from './containers/createTenantRequestWebhookUrl.js';

export interface CreateTenantRequest {
  /** Legal name of the business tenant. */
  businessLegalName: string;
  /** Doing Business As name (optional). */
  businessDba?: CreateTenantRequestBusinessDba;
  /** Country code for the business address. */
  businessAddressCountry?: CreateTenantRequestBusinessAddressCountry;
  /** Street address line 1 (for businesses). */
  businessStreetAddress1?: CreateTenantRequestBusinessStreetAddress1;
  /** Street address line 2 (for businesses). */
  businessStreetAddress2?: CreateTenantRequestBusinessStreetAddress2;
  /** City (for businesses). */
  businessCity?: CreateTenantRequestBusinessCity;
  /** State/region (for businesses). */
  businessState?: CreateTenantRequestBusinessState;
  /** Legal Entity Identifier (for businesses). */
  businessLegalEntityIdentifier?: CreateTenantRequestBusinessLegalEntityIdentifier;
  /** Webhook URL that will receive events related to this tenant (optional). */
  webhookUrl?: CreateTenantRequestWebhookUrl;
}

export const createTenantRequestSchema: Schema<CreateTenantRequest> = lazy(() =>
  object({
    businessLegalName: ['business_legal_name', string()],
    businessDba: [
      'business_dba',
      optional(createTenantRequestBusinessDbaSchema),
    ],
    businessAddressCountry: [
      'business_address_country',
      optional(createTenantRequestBusinessAddressCountrySchema),
    ],
    businessStreetAddress1: [
      'business_street_address1',
      optional(createTenantRequestBusinessStreetAddress1Schema),
    ],
    businessStreetAddress2: [
      'business_street_address2',
      optional(createTenantRequestBusinessStreetAddress2Schema),
    ],
    businessCity: [
      'business_city',
      optional(createTenantRequestBusinessCitySchema),
    ],
    businessState: [
      'business_state',
      optional(createTenantRequestBusinessStateSchema),
    ],
    businessLegalEntityIdentifier: [
      'business_legal_entity_identifier',
      optional(createTenantRequestBusinessLegalEntityIdentifierSchema),
    ],
    webhookUrl: ['webhook_url', optional(createTenantRequestWebhookUrlSchema)],
  })
);
