/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';
import { Type3Enum, type3EnumSchema } from './type3Enum.js';

export interface CreateWalletRequest {
  /** ID of the workspace. */
  workspaceId: string;
  /** ID of the tenant that owns this wallet (optional). At most one of tenant_id or counterparty_id may be provided. */
  tenantId?: string;
  /** ID of the counterparty that owns this wallet (optional). At most one of tenant_id or counterparty_id may be provided. */
  counterpartyId?: string;
  /** Name of the wallet account. */
  name: string;
  /** Wallet type. */
  type: Type3Enum;
  /** A cryptographic stamp used to verify the integrity and authenticity of the request. This ensures the request was signed by an authorized key. See Documentation > Signing for more details. */
  signature: string;
}

export const createWalletRequestSchema: Schema<CreateWalletRequest> = object({
  workspaceId: ['workspace_id', string()],
  tenantId: ['tenant_id', optional(string())],
  counterpartyId: ['counterparty_id', optional(string())],
  name: ['name', string()],
  type: ['type', type3EnumSchema],
  signature: ['signature', string()],
});
