/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CreateBankRequest {
  /** ID of the workspace. */
  workspaceId?: string;
  /** Name of the bank account. */
  name: string;
  /** Name of the bank. */
  bankName: string;
  /** Type of bank code (e.g., 'SWIFT'). */
  bankCodeType: string;
  /** Bank identifier code value. */
  bankIdentifierCode: string;
  /** Bank account number (IBAN, etc). */
  bankAccountNumber: string;
  /** ID of the counterparty owner. */
  counterpartyId?: string;
}

export const createBankRequestSchema: Schema<CreateBankRequest> = object({
  workspaceId: ['workspace_id', optional(string())],
  name: ['name', string()],
  bankName: ['bank_name', string()],
  bankCodeType: ['bank_code_type', string()],
  bankIdentifierCode: ['bank_identifier_code', string()],
  bankAccountNumber: ['bank_account_number', string()],
  counterpartyId: ['counterparty_id', optional(string())],
});
