/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface CreateWithdrawalRequest {
  /** Destination account ID. */
  toAccountId: string;
  /** Source currency code. */
  fromCurrency: string;
  /** Destination currency code. */
  toCurrency: string;
  /** Amount to send. Required if to_amount is missing. */
  fromAmount?: string;
  /** Amount to receive. Required if from_amount is missing. */
  toAmount?: string;
  /** Optional tenant ID. */
  tenantId?: string;
  /** Source account ID. */
  fromAccountId: string;
  /** Network for the withdrawal. */
  fromNetwork: string;
}

export const createWithdrawalRequestSchema: Schema<CreateWithdrawalRequest> = object(
  {
    toAccountId: ['to_account_id', string()],
    fromCurrency: ['from_currency', string()],
    toCurrency: ['to_currency', string()],
    fromAmount: ['from_amount', optional(string())],
    toAmount: ['to_amount', optional(string())],
    tenantId: ['tenant_id', optional(string())],
    fromAccountId: ['from_account_id', string()],
    fromNetwork: ['from_network', string()],
  }
);
