/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { AccountSafe, accountSafeSchema } from './accountSafe.js';

export interface CreateBankResponse {
  data: AccountSafe;
}

export const createBankResponseSchema: Schema<CreateBankResponse> = lazy(() =>
  object({ data: ['data', accountSafeSchema] })
);
