/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, number, object, Schema, string } from '../schema.js';
import {
  CurrencyNetwork,
  currencyNetworkSchema,
} from './containers/currencyNetwork.js';

export interface Currency {
  /** Display name for the currency (e.g., 'Circle USD') */
  name: string;
  /** Currency code/key (e.g., 'USDC', 'USD') */
  key: string;
  /** Number of decimal places for the currency */
  decimals: number;
  /** Blockchain network (e.g., 'POLYGON') or null for fiat currencies. See GET /networks for supported values. */
  network: CurrencyNetwork;
}

export const currencySchema: Schema<Currency> = lazy(() =>
  object({
    name: ['name', string()],
    key: ['key', string()],
    decimals: ['decimals', number()],
    network: ['network', currencyNetworkSchema],
  })
);
