/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Currency, currencySchema } from './currency.js';

export interface CurrenciesResponse {
  /** List of all supported currencies */
  data: Currency[];
}

export const currenciesResponseSchema: Schema<CurrenciesResponse> = lazy(() =>
  object({ data: ['data', array(currencySchema)] })
);
