/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema, string } from '../schema.js';
import { tenantBusinessAddressCountrySchema } from './containers/tenantBusinessAddressCountry.js';
import { tenantBusinessCitySchema } from './containers/tenantBusinessCity.js';
import { tenantBusinessDbaSchema } from './containers/tenantBusinessDba.js';
import { tenantBusinessLegalEntityIdentifierSchema } from './containers/tenantBusinessLegalEntityIdentifier.js';
import { tenantBusinessLegalNameSchema } from './containers/tenantBusinessLegalName.js';
import { tenantBusinessStateSchema } from './containers/tenantBusinessState.js';
import { tenantBusinessStreetAddress1Schema } from './containers/tenantBusinessStreetAddress1.js';
import { tenantBusinessStreetAddress2Schema } from './containers/tenantBusinessStreetAddress2.js';
import { tenantCountrySchema } from './containers/tenantCountry.js';
import { tenantWebhookUrlSchema } from './containers/tenantWebhookUrl.js';
import { Tenant } from './tenant.js';

export interface Data8 extends Tenant {

}

export const data8Schema: Schema<Data8> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    businessLegalName: ['business_legal_name', tenantBusinessLegalNameSchema],
    businessDba: ['business_dba', tenantBusinessDbaSchema],
    businessAddressCountry: [
      'business_address_country',
      tenantBusinessAddressCountrySchema,
    ],
    businessStreetAddress1: [
      'business_street_address1',
      tenantBusinessStreetAddress1Schema,
    ],
    businessStreetAddress2: [
      'business_street_address2',
      tenantBusinessStreetAddress2Schema,
    ],
    businessCity: ['business_city', tenantBusinessCitySchema],
    businessState: ['business_state', tenantBusinessStateSchema],
    businessLegalEntityIdentifier: [
      'business_legal_entity_identifier',
      tenantBusinessLegalEntityIdentifierSchema,
    ],
    country: ['country', tenantCountrySchema],
    webhookUrl: ['webhook_url', tenantWebhookUrlSchema],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
