/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { classificationEnumSchema } from './classificationEnum.js';
import { counterpartyBusinessAddressCountrySchema } from './containers/counterpartyBusinessAddressCountry.js';
import { counterpartyBusinessCitySchema } from './containers/counterpartyBusinessCity.js';
import { counterpartyBusinessDbaSchema } from './containers/counterpartyBusinessDba.js';
import { counterpartyBusinessLegalEntityIdentifierSchema } from './containers/counterpartyBusinessLegalEntityIdentifier.js';
import { counterpartyBusinessLegalNameSchema } from './containers/counterpartyBusinessLegalName.js';
import { counterpartyBusinessStateSchema } from './containers/counterpartyBusinessState.js';
import { counterpartyBusinessStreetAddress1Schema } from './containers/counterpartyBusinessStreetAddress1.js';
import { counterpartyBusinessStreetAddress2Schema } from './containers/counterpartyBusinessStreetAddress2.js';
import { counterpartyIndividualAddressCountrySchema } from './containers/counterpartyIndividualAddressCountry.js';
import { counterpartyIndividualCitySchema } from './containers/counterpartyIndividualCity.js';
import { counterpartyIndividualDateOfBirthSchema } from './containers/counterpartyIndividualDateOfBirth.js';
import { counterpartyIndividualFirstNameSchema } from './containers/counterpartyIndividualFirstName.js';
import { counterpartyIndividualLastNameSchema } from './containers/counterpartyIndividualLastName.js';
import { counterpartyIndividualNationalIdentificationNumberSchema } from './containers/counterpartyIndividualNationalIdentificationNumber.js';
import { counterpartyIndividualPostalCodeSchema } from './containers/counterpartyIndividualPostalCode.js';
import { counterpartyIndividualStateSchema } from './containers/counterpartyIndividualState.js';
import { counterpartyIndividualStreetAddress1Schema } from './containers/counterpartyIndividualStreetAddress1.js';
import { counterpartyIndividualStreetAddress2Schema } from './containers/counterpartyIndividualStreetAddress2.js';
import { counterpartyTenantIdSchema } from './containers/counterpartyTenantId.js';
import { Counterparty } from './counterparty.js';

export interface Data extends Counterparty {

}

export const dataSchema: Schema<Data> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    classification: ['classification', classificationEnumSchema],
    tenantId: ['tenant_id', optional(counterpartyTenantIdSchema)],
    individualFirstName: [
      'individual_first_name',
      optional(counterpartyIndividualFirstNameSchema),
    ],
    individualLastName: [
      'individual_last_name',
      optional(counterpartyIndividualLastNameSchema),
    ],
    individualAddressCountry: [
      'individual_address_country',
      optional(counterpartyIndividualAddressCountrySchema),
    ],
    individualDateOfBirth: [
      'individual_date_of_birth',
      optional(counterpartyIndividualDateOfBirthSchema),
    ],
    individualNationalIdentificationNumber: [
      'individual_national_identification_number',
      optional(counterpartyIndividualNationalIdentificationNumberSchema),
    ],
    individualStreetAddress1: [
      'individual_street_address1',
      optional(counterpartyIndividualStreetAddress1Schema),
    ],
    individualStreetAddress2: [
      'individual_street_address2',
      optional(counterpartyIndividualStreetAddress2Schema),
    ],
    individualCity: [
      'individual_city',
      optional(counterpartyIndividualCitySchema),
    ],
    individualState: [
      'individual_state',
      optional(counterpartyIndividualStateSchema),
    ],
    individualPostalCode: [
      'individual_postal_code',
      optional(counterpartyIndividualPostalCodeSchema),
    ],
    businessLegalName: [
      'business_legal_name',
      optional(counterpartyBusinessLegalNameSchema),
    ],
    businessDba: ['business_dba', optional(counterpartyBusinessDbaSchema)],
    businessAddressCountry: [
      'business_address_country',
      optional(counterpartyBusinessAddressCountrySchema),
    ],
    businessStreetAddress1: [
      'business_street_address1',
      optional(counterpartyBusinessStreetAddress1Schema),
    ],
    businessStreetAddress2: [
      'business_street_address2',
      optional(counterpartyBusinessStreetAddress2Schema),
    ],
    businessCity: ['business_city', optional(counterpartyBusinessCitySchema)],
    businessState: [
      'business_state',
      optional(counterpartyBusinessStateSchema),
    ],
    businessLegalEntityIdentifier: [
      'business_legal_entity_identifier',
      optional(counterpartyBusinessLegalEntityIdentifierSchema),
    ],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
