/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import { paymentBalanceReservedAtSchema } from './containers/paymentBalanceReservedAt.js';
import { paymentBalanceStatusSchema } from './containers/paymentBalanceStatus.js';
import { paymentBeneficiaryAccountIdSchema } from './containers/paymentBeneficiaryAccountId.js';
import { paymentFromNetworkSchema } from './containers/paymentFromNetwork.js';
import { paymentOrganizationReferenceIdSchema } from './containers/paymentOrganizationReferenceId.js';
import { paymentOriginatorAccountIdSchema } from './containers/paymentOriginatorAccountId.js';
import { paymentRiskReviewedAtSchema } from './containers/paymentRiskReviewedAt.js';
import { paymentRiskReviewedBySchema } from './containers/paymentRiskReviewedBy.js';
import { paymentSourceAccountIdSchema } from './containers/paymentSourceAccountId.js';
import { paymentToNetworkSchema } from './containers/paymentToNetwork.js';
import { directionEnumSchema } from './directionEnum.js';
import { Payment } from './payment.js';
import { paymentTypeEnumSchema } from './paymentTypeEnum.js';
import { riskStatusEnumSchema } from './riskStatusEnum.js';
import { stepSchema } from './step.js';

export interface Data6 extends Payment {

}

export const data6Schema: Schema<Data6> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    organizationReferenceId: [
      'organization_reference_id',
      optional(paymentOrganizationReferenceIdSchema),
    ],
    direction: ['direction', directionEnumSchema],
    paymentType: ['payment_type', paymentTypeEnumSchema],
    sourceAccountId: [
      'source_account_id',
      optional(paymentSourceAccountIdSchema),
    ],
    originatorAccountId: [
      'originator_account_id',
      optional(paymentOriginatorAccountIdSchema),
    ],
    beneficiaryAccountId: [
      'beneficiary_account_id',
      optional(paymentBeneficiaryAccountIdSchema),
    ],
    fromAmount: ['from_amount', string()],
    fromCurrency: ['from_currency', string()],
    fromNetwork: ['from_network', optional(paymentFromNetworkSchema)],
    toAmount: ['to_amount', string()],
    toCurrency: ['to_currency', string()],
    toNetwork: ['to_network', optional(paymentToNetworkSchema)],
    riskStatus: ['risk_status', riskStatusEnumSchema],
    riskStatusReasons: [
      'risk_status_reasons',
      optional(nullable(array(nullable(string())))),
    ],
    riskReviewedBy: ['risk_reviewed_by', optional(paymentRiskReviewedBySchema)],
    riskReviewedAt: ['risk_reviewed_at', optional(paymentRiskReviewedAtSchema)],
    balanceStatus: [
      'balance_status',
      optional(nullable(paymentBalanceStatusSchema)),
    ],
    balanceReservedAt: [
      'balance_reserved_at',
      optional(paymentBalanceReservedAtSchema),
    ],
    steps: ['steps', optional(array(stepSchema))],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    expiresAt: ['expires_at', string()],
  })
);
