/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema, string } from '../schema.js';
import {
  Data7BalanceReservedAt,
  data7BalanceReservedAtSchema,
} from './containers/data7BalanceReservedAt.js';
import {
  Data7BalanceStatus,
  data7BalanceStatusSchema,
} from './containers/data7BalanceStatus.js';
import {
  Data7BeneficiaryAccountId,
  data7BeneficiaryAccountIdSchema,
} from './containers/data7BeneficiaryAccountId.js';
import {
  Data7FromNetwork,
  data7FromNetworkSchema,
} from './containers/data7FromNetwork.js';
import {
  Data7OrganizationReferenceId,
  data7OrganizationReferenceIdSchema,
} from './containers/data7OrganizationReferenceId.js';
import {
  Data7OriginatorAccountId,
  data7OriginatorAccountIdSchema,
} from './containers/data7OriginatorAccountId.js';
import {
  Data7RiskReviewedAt,
  data7RiskReviewedAtSchema,
} from './containers/data7RiskReviewedAt.js';
import {
  Data7RiskReviewedBy,
  data7RiskReviewedBySchema,
} from './containers/data7RiskReviewedBy.js';
import {
  Data7RiskStatusReasons,
  data7RiskStatusReasonsSchema,
} from './containers/data7RiskStatusReasons.js';
import {
  Data7SourceAccountId,
  data7SourceAccountIdSchema,
} from './containers/data7SourceAccountId.js';
import {
  Data7ToNetwork,
  data7ToNetworkSchema,
} from './containers/data7ToNetwork.js';
import { Direction1Enum, direction1EnumSchema } from './direction1Enum.js';
import { PaymentTypeEnum, paymentTypeEnumSchema } from './paymentTypeEnum.js';
import { RiskStatusEnum, riskStatusEnumSchema } from './riskStatusEnum.js';
import { Step, stepSchema } from './step.js';

export interface Data7 {
  /** Unique identifier for the payment */
  id: string;
  /** Workspace ID the payment belongs to */
  workspaceId: string;
  /** Optional external reference ID. */
  organizationReferenceId?: Data7OrganizationReferenceId;
  /** Payment direction: 'inbound', 'outbound', 'internal' */
  direction: Direction1Enum;
  /** Type of payment operation: 'payment' (wallet-to-wallet), 'offramp' (crypto-to-fiat), 'onramp' (fiat-to-crypto), 'withdrawal', 'deposit', or 'transfer'. */
  paymentType: PaymentTypeEnum;
  /** ID of the source account (paying wallet). */
  sourceAccountId?: Data7SourceAccountId;
  /** ID of the originator account. */
  originatorAccountId?: Data7OriginatorAccountId;
  /** ID of the beneficiary account. */
  beneficiaryAccountId?: Data7BeneficiaryAccountId;
  /** Amount to send. */
  fromAmount: string;
  /** Source currency code. */
  fromCurrency: string;
  /** Source blockchain network. */
  fromNetwork?: Data7FromNetwork;
  /** Amount to receive. */
  toAmount: string;
  /** Destination currency code. */
  toCurrency: string;
  /** Destination blockchain network. */
  toNetwork?: Data7ToNetwork;
  /** Current risk status. */
  riskStatus: RiskStatusEnum;
  /** List of reasons for risk status. */
  riskStatusReasons?: Data7RiskStatusReasons;
  /** ID of the user who performed the risk review. */
  riskReviewedBy?: Data7RiskReviewedBy;
  /** Timestamp of risk review. */
  riskReviewedAt?: Data7RiskReviewedAt;
  /** Balance reservation status. */
  balanceStatus?: Data7BalanceStatus;
  /** Timestamp when balance was reserved. */
  balanceReservedAt?: Data7BalanceReservedAt;
  /** Optional list of system-generated steps that make up this payment/transfer route. */
  steps?: Step[];
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** ISO 8601 timestamp of last update. */
  updatedAt: string;
  /** ISO 8601 timestamp when the quote expires. */
  expiresAt: string;
}

export const data7Schema: Schema<Data7> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    organizationReferenceId: [
      'organization_reference_id',
      optional(data7OrganizationReferenceIdSchema),
    ],
    direction: ['direction', direction1EnumSchema],
    paymentType: ['payment_type', paymentTypeEnumSchema],
    sourceAccountId: [
      'source_account_id',
      optional(data7SourceAccountIdSchema),
    ],
    originatorAccountId: [
      'originator_account_id',
      optional(data7OriginatorAccountIdSchema),
    ],
    beneficiaryAccountId: [
      'beneficiary_account_id',
      optional(data7BeneficiaryAccountIdSchema),
    ],
    fromAmount: ['from_amount', string()],
    fromCurrency: ['from_currency', string()],
    fromNetwork: ['from_network', optional(data7FromNetworkSchema)],
    toAmount: ['to_amount', string()],
    toCurrency: ['to_currency', string()],
    toNetwork: ['to_network', optional(data7ToNetworkSchema)],
    riskStatus: ['risk_status', riskStatusEnumSchema],
    riskStatusReasons: [
      'risk_status_reasons',
      optional(data7RiskStatusReasonsSchema),
    ],
    riskReviewedBy: ['risk_reviewed_by', optional(data7RiskReviewedBySchema)],
    riskReviewedAt: ['risk_reviewed_at', optional(data7RiskReviewedAtSchema)],
    balanceStatus: ['balance_status', optional(data7BalanceStatusSchema)],
    balanceReservedAt: [
      'balance_reserved_at',
      optional(data7BalanceReservedAtSchema),
    ],
    steps: ['steps', optional(array(stepSchema))],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    expiresAt: ['expires_at', string()],
  })
);
