/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for DirectionEnum
 */
export enum DirectionEnum {
  Inbound = 'inbound',
  Outbound = 'outbound',
  Internal = 'internal',
}

/**
 * Schema for DirectionEnum
 */
export const directionEnumSchema: Schema<DirectionEnum> = stringEnum(
  DirectionEnum
);
