/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Direction1Enum
 */
export enum Direction1Enum {
  Inbound = 'inbound',
  Outbound = 'outbound',
  Internal = 'internal',
}

/**
 * Schema for Direction1Enum
 */
export const direction1EnumSchema: Schema<Direction1Enum> = stringEnum(
  Direction1Enum
);
