/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { TurnkeyStamp, turnkeyStampSchema } from './turnkeyStamp.js';

export interface ExecutePaymentRequestDto {
  /** Signature for the specified payment step. */
  signature: string;
  /** Optional Turnkey stamp data for server-side signing */
  turnkeyStamp?: TurnkeyStamp;
}

export const executePaymentRequestDtoSchema: Schema<ExecutePaymentRequestDto> = lazy(
  () =>
    object({
      signature: ['signature', string()],
      turnkeyStamp: ['turnkey_stamp', optional(turnkeyStampSchema)],
    })
);
