/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { FeeMetadata, feeMetadataSchema } from './containers/feeMetadata.js';

export interface Fee {
  /** Fee amount. */
  feeAmount: string;
  /** Fee currency code. */
  feeCurrency: string;
  /** Fee type (e.g., 'gas', 'provider'). */
  type: string;
  /** Additional metadata for the fee. */
  metadata?: FeeMetadata;
}

export const feeSchema: Schema<Fee> = lazy(() =>
  object({
    feeAmount: ['fee_amount', string()],
    feeCurrency: ['fee_currency', string()],
    type: ['type', string()],
    metadata: ['metadata', optional(feeMetadataSchema)],
  })
);
