/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import { Fee1Metadata, fee1MetadataSchema } from './containers/fee1Metadata.js';

export interface Fee1 {
  /** Fee amount. */
  feeAmount: string;
  /** Fee currency code. */
  feeCurrency: string;
  /** Fee type (e.g., 'gas', 'provider'). */
  type: string;
  /** Additional metadata for the fee (JSON). */
  metadata?: Fee1Metadata;
}

export const fee1Schema: Schema<Fee1> = lazy(() =>
  object({
    feeAmount: ['fee_amount', string()],
    feeCurrency: ['fee_currency', string()],
    type: ['type', string()],
    metadata: ['metadata', optional(fee1MetadataSchema)],
  })
);
