/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface Network {
  /** Network key/identifier (e.g., 'POLYGON', 'ETHEREUM') */
  key: string;
  /** Display name for the network (e.g., 'Polygon') */
  name: string;
}

export const networkSchema: Schema<Network> = object({
  key: ['key', string()],
  name: ['name', string()],
});
