/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Network, networkSchema } from './network.js';

export interface NetworksResponse {
  /** List of all supported networks */
  data: Network[];
}

export const networksResponseSchema: Schema<NetworksResponse> = lazy(() =>
  object({ data: ['data', array(networkSchema)] })
);
