/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, number, object, Schema } from '../schema.js';

/** Pagination details */
export interface Pagination {
  /** Current page number */
  page: number;
  /** Items per page */
  limit: number;
  /** Total number of items */
  total: number;
  /** Total number of pages */
  totalPages: number;
  /** Has next page */
  hasNext: boolean;
  /** Has previous page */
  hasPrev: boolean;
}

export const paginationSchema: Schema<Pagination> = object({
  page: ['page', number()],
  limit: ['limit', number()],
  total: ['total', number()],
  totalPages: ['total_pages', number()],
  hasNext: ['has_next', boolean()],
  hasPrev: ['has_prev', boolean()],
});
