/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentTypeEnum
 */
export enum PaymentTypeEnum {
  Withdrawal = 'withdrawal',
  Deposit = 'deposit',
  Onramp = 'onramp',
  Offramp = 'offramp',
  Payment = 'payment',
  Transfer = 'transfer',
}

/**
 * Schema for PaymentTypeEnum
 */
export const paymentTypeEnumSchema: Schema<PaymentTypeEnum> = stringEnum(
  PaymentTypeEnum
);
