/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Data6, data6Schema } from './data6.js';

export interface PaymentResponse {
  data: Data6;
}

export const paymentResponseSchema: Schema<PaymentResponse> = lazy(() =>
  object({ data: ['data', data6Schema] })
);
