/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  isMappedValueValidForSchema,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  PaymentBalanceReservedAt,
  paymentBalanceReservedAtSchema,
} from './containers/paymentBalanceReservedAt.js';
import {
  PaymentBalanceStatus,
  paymentBalanceStatusSchema,
} from './containers/paymentBalanceStatus.js';
import {
  PaymentBeneficiaryAccountId,
  paymentBeneficiaryAccountIdSchema,
} from './containers/paymentBeneficiaryAccountId.js';
import {
  PaymentFromNetwork,
  paymentFromNetworkSchema,
} from './containers/paymentFromNetwork.js';
import {
  PaymentOrganizationReferenceId,
  paymentOrganizationReferenceIdSchema,
} from './containers/paymentOrganizationReferenceId.js';
import {
  PaymentOriginatorAccountId,
  paymentOriginatorAccountIdSchema,
} from './containers/paymentOriginatorAccountId.js';
import {
  PaymentRiskReviewedAt,
  paymentRiskReviewedAtSchema,
} from './containers/paymentRiskReviewedAt.js';
import {
  PaymentRiskReviewedBy,
  paymentRiskReviewedBySchema,
} from './containers/paymentRiskReviewedBy.js';
import {
  PaymentSourceAccountId,
  paymentSourceAccountIdSchema,
} from './containers/paymentSourceAccountId.js';
import {
  PaymentToNetwork,
  paymentToNetworkSchema,
} from './containers/paymentToNetwork.js';
import { Data6, data6Schema } from './data6.js';
import { DirectionEnum, directionEnumSchema } from './directionEnum.js';
import { PaymentTypeEnum, paymentTypeEnumSchema } from './paymentTypeEnum.js';
import { RiskStatusEnum, riskStatusEnumSchema } from './riskStatusEnum.js';
import { Step, stepSchema } from './step.js';

export interface Payment {
  /** Unique identifier for the payment. */
  id: string;
  /** Workspace ID the payment belongs to. */
  workspaceId: string;
  /** Optional external reference ID. */
  organizationReferenceId?: PaymentOrganizationReferenceId;
  /** Payment direction: 'inbound', 'outbound', 'internal'. */
  direction: DirectionEnum;
  /** Type of payment operation: 'payment' (wallet-to-wallet), 'offramp' (crypto-to-fiat), 'onramp' (fiat-to-crypto), 'withdrawal', 'deposit', or 'transfer'. */
  paymentType: PaymentTypeEnum;
  /** ID of the source account (paying wallet). */
  sourceAccountId?: PaymentSourceAccountId;
  /** ID of the originator account. */
  originatorAccountId?: PaymentOriginatorAccountId;
  /** ID of the beneficiary account. */
  beneficiaryAccountId?: PaymentBeneficiaryAccountId;
  /** Amount to send. */
  fromAmount: string;
  /** Source currency code. */
  fromCurrency: string;
  /** Source blockchain network. */
  fromNetwork?: PaymentFromNetwork;
  /** Amount to receive. */
  toAmount: string;
  /** Destination currency code. */
  toCurrency: string;
  /** Destination blockchain network. */
  toNetwork?: PaymentToNetwork;
  /** Current risk status. */
  riskStatus: RiskStatusEnum;
  /** List of reasons for risk status. */
  riskStatusReasons?: (string | null)[] | null;
  /** ID of the user who performed the risk review. */
  riskReviewedBy?: PaymentRiskReviewedBy;
  /** Timestamp of risk review. */
  riskReviewedAt?: PaymentRiskReviewedAt;
  /** Balance reservation status. */
  balanceStatus?: PaymentBalanceStatus | null;
  /** Timestamp when balance was reserved. */
  balanceReservedAt?: PaymentBalanceReservedAt;
  /** Optional list of system-generated steps that make up this payment/transfer route. */
  steps?: Step[];
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** ISO 8601 timestamp of last update. */
  updatedAt: string;
  /** ISO 8601 timestamp when the quote expires. */
  expiresAt: string;
}

export namespace Payment {
  /**
   * Validation method to check if the given Payment instance is also a Data6.
   */
  export function isData6(value: Payment): value is Data6 {
    return isMappedValueValidForSchema(value, data6Schema);
  }
}

export const paymentSchema: Schema<Payment> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    organizationReferenceId: [
      'organization_reference_id',
      optional(paymentOrganizationReferenceIdSchema),
    ],
    direction: ['direction', directionEnumSchema],
    paymentType: ['payment_type', paymentTypeEnumSchema],
    sourceAccountId: [
      'source_account_id',
      optional(paymentSourceAccountIdSchema),
    ],
    originatorAccountId: [
      'originator_account_id',
      optional(paymentOriginatorAccountIdSchema),
    ],
    beneficiaryAccountId: [
      'beneficiary_account_id',
      optional(paymentBeneficiaryAccountIdSchema),
    ],
    fromAmount: ['from_amount', string()],
    fromCurrency: ['from_currency', string()],
    fromNetwork: ['from_network', optional(paymentFromNetworkSchema)],
    toAmount: ['to_amount', string()],
    toCurrency: ['to_currency', string()],
    toNetwork: ['to_network', optional(paymentToNetworkSchema)],
    riskStatus: ['risk_status', riskStatusEnumSchema],
    riskStatusReasons: [
      'risk_status_reasons',
      optional(nullable(array(nullable(string())))),
    ],
    riskReviewedBy: ['risk_reviewed_by', optional(paymentRiskReviewedBySchema)],
    riskReviewedAt: ['risk_reviewed_at', optional(paymentRiskReviewedAtSchema)],
    balanceStatus: [
      'balance_status',
      optional(nullable(paymentBalanceStatusSchema)),
    ],
    balanceReservedAt: [
      'balance_reserved_at',
      optional(paymentBalanceReservedAtSchema),
    ],
    steps: ['steps', optional(array(stepSchema))],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    expiresAt: ['expires_at', string()],
  })
);
