/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for PaymentType3Enum
 */
export enum PaymentType3Enum {
  Withdrawal = 'withdrawal',
  Deposit = 'deposit',
  Onramp = 'onramp',
  Offramp = 'offramp',
  Payment = 'payment',
  Transfer = 'transfer',
}

/**
 * Schema for PaymentType3Enum
 */
export const paymentType3EnumSchema: Schema<PaymentType3Enum> = stringEnum(
  PaymentType3Enum
);
