/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema.js';
import { Data7, data7Schema } from './data7.js';
import { Pagination, paginationSchema } from './pagination.js';

export interface PaymentListResponse {
  data: Data7[];
  /** Pagination details */
  pagination?: Pagination;
}

export const paymentListResponseSchema: Schema<PaymentListResponse> = lazy(() =>
  object({
    data: ['data', array(data7Schema)],
    pagination: ['pagination', optional(paginationSchema)],
  })
);
