/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProviderKeyEnum
 */
export enum ProviderKeyEnum {
  Alfred = 'alfred',
  CircleMint = 'circle_mint',
}

/**
 * Schema for ProviderKeyEnum
 */
export const providerKeyEnumSchema: Schema<ProviderKeyEnum> = stringEnum(
  ProviderKeyEnum
);
