/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for ProviderKey1Enum
 */
export enum ProviderKey1Enum {
  Alfred = 'alfred',
  CircleMint = 'circle_mint',
}

/**
 * Schema for ProviderKey1Enum
 */
export const providerKey1EnumSchema: Schema<ProviderKey1Enum> = stringEnum(
  ProviderKey1Enum
);
