/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface Response {
  status?: string;
  gitSha?: string;
  env?: string;
}

export const responseSchema: Schema<Response> = object({
  status: ['status', optional(string())],
  gitSha: ['gitSha', optional(string())],
  env: ['env', optional(string())],
});
