/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { boolean, object, Schema } from '../schema.js';

export interface ReviewPaymentRequest {
  /** Whether to approve (true) or reject (false) the payment. */
  isApproved: boolean;
}

export const reviewPaymentRequestSchema: Schema<ReviewPaymentRequest> = object({
  isApproved: ['is_approved', boolean()],
});
