/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for RiskStatusEnum
 */
export enum RiskStatusEnum {
  Unchecked = 'unchecked',
  AwaitingDecision = 'awaiting_decision',
  Approved = 'approved',
  Rejected = 'rejected',
}

/**
 * Schema for RiskStatusEnum
 */
export const riskStatusEnumSchema: Schema<RiskStatusEnum> = stringEnum(
  RiskStatusEnum
);
