/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StatusEnum
 */
export enum StatusEnum {
  Created = 'created',
  Submitted = 'submitted',
  Confirmed = 'confirmed',
  Finalized = 'finalized',
  Failed = 'failed',
}

/**
 * Schema for StatusEnum
 */
export const statusEnumSchema: Schema<StatusEnum> = stringEnum(StatusEnum);
