/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for StepTypeEnum
 */
export enum StepTypeEnum {
  StablecoinTransfer = 'stablecoin_transfer',
  Offramp = 'offramp',
  Onramp = 'onramp',
  FiatTransfer = 'fiat_transfer',
}

/**
 * Schema for StepTypeEnum
 */
export const stepTypeEnumSchema: Schema<StepTypeEnum> = stringEnum(
  StepTypeEnum
);
