/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  StepCompletedAt,
  stepCompletedAtSchema,
} from './containers/stepCompletedAt.js';
import {
  StepConfirmedAt,
  stepConfirmedAtSchema,
} from './containers/stepConfirmedAt.js';
import { StepFailedAt, stepFailedAtSchema } from './containers/stepFailedAt.js';
import {
  StepFinalizedAt,
  stepFinalizedAtSchema,
} from './containers/stepFinalizedAt.js';
import {
  StepFromAccountAssetId,
  stepFromAccountAssetIdSchema,
} from './containers/stepFromAccountAssetId.js';
import {
  StepFromAccountId,
  stepFromAccountIdSchema,
} from './containers/stepFromAccountId.js';
import {
  StepProviderKey,
  stepProviderKeySchema,
} from './containers/stepProviderKey.js';
import {
  StepStatusReasons,
  stepStatusReasonsSchema,
} from './containers/stepStatusReasons.js';
import {
  StepSubmittedAt,
  stepSubmittedAtSchema,
} from './containers/stepSubmittedAt.js';
import {
  StepToAccountAssetId,
  stepToAccountAssetIdSchema,
} from './containers/stepToAccountAssetId.js';
import {
  StepToAccountId,
  stepToAccountIdSchema,
} from './containers/stepToAccountId.js';
import {
  StepTransactionHash,
  stepTransactionHashSchema,
} from './containers/stepTransactionHash.js';
import { Fee1, fee1Schema } from './fee1.js';
import { Status1Enum, status1EnumSchema } from './status1Enum.js';
import { StepTypeEnum, stepTypeEnumSchema } from './stepTypeEnum.js';

export interface Step {
  /** Unique identifier for the step. */
  id: string;
  /** ID of the parent payment/transfer. */
  transferId: string;
  /** Step sequence number (0-based or 1-based). */
  stepSequence: number;
  /** Step type: 'stablecoin_transfer', 'offramp', 'onramp', 'fiat_transfer'. */
  stepType: StepTypeEnum;
  /** Source account asset ID for this step. */
  fromAccountAssetId?: StepFromAccountAssetId;
  /** Source account ID for this step. */
  fromAccountId?: StepFromAccountId;
  /** Amount sent in this step. */
  fromAmount: string;
  /** Currency code sent in this step. */
  fromCurrency: string;
  /** Destination account asset ID for this step. */
  toAccountAssetId?: StepToAccountAssetId;
  /** Destination account ID for this step. */
  toAccountId?: StepToAccountId;
  /** Amount received in this step. */
  toAmount: string;
  /** Currency code received in this step. */
  toCurrency: string;
  /** Blockchain transaction hash (for crypto steps). */
  transactionHash?: StepTransactionHash;
  /** List of fees associated with this step. */
  fees?: Fee1[];
  /** Provider key used for this step (if applicable). */
  providerKey?: StepProviderKey;
  /** Step status: 'created', 'submitted', 'confirmed', 'finalized', 'failed'. */
  status: Status1Enum;
  /** Array of reasons explaining the current status (if any). */
  statusReasons?: StepStatusReasons;
  /** Submitted timestamp. */
  submittedAt?: StepSubmittedAt;
  /** Confirmed timestamp. */
  confirmedAt?: StepConfirmedAt;
  /** Finalized timestamp. */
  finalizedAt?: StepFinalizedAt;
  /** Completed timestamp. */
  completedAt?: StepCompletedAt;
  /** Failed timestamp. */
  failedAt?: StepFailedAt;
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** ISO 8601 timestamp of last update. */
  updatedAt: string;
}

export const stepSchema: Schema<Step> = lazy(() =>
  object({
    id: ['id', string()],
    transferId: ['transfer_id', string()],
    stepSequence: ['step_sequence', number()],
    stepType: ['step_type', stepTypeEnumSchema],
    fromAccountAssetId: [
      'from_account_asset_id',
      optional(stepFromAccountAssetIdSchema),
    ],
    fromAccountId: ['from_account_id', optional(stepFromAccountIdSchema)],
    fromAmount: ['from_amount', string()],
    fromCurrency: ['from_currency', string()],
    toAccountAssetId: [
      'to_account_asset_id',
      optional(stepToAccountAssetIdSchema),
    ],
    toAccountId: ['to_account_id', optional(stepToAccountIdSchema)],
    toAmount: ['to_amount', string()],
    toCurrency: ['to_currency', string()],
    transactionHash: ['transaction_hash', optional(stepTransactionHashSchema)],
    fees: ['fees', optional(array(fee1Schema))],
    providerKey: ['provider_key', optional(stepProviderKeySchema)],
    status: ['status', status1EnumSchema],
    statusReasons: ['status_reasons', optional(stepStatusReasonsSchema)],
    submittedAt: ['submitted_at', optional(stepSubmittedAtSchema)],
    confirmedAt: ['confirmed_at', optional(stepConfirmedAtSchema)],
    finalizedAt: ['finalized_at', optional(stepFinalizedAtSchema)],
    completedAt: ['completed_at', optional(stepCompletedAtSchema)],
    failedAt: ['failed_at', optional(stepFailedAtSchema)],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
