/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  isMappedValueValidForSchema,
  lazy,
  object,
  Schema,
  string,
} from '../schema.js';
import {
  TenantBusinessAddressCountry,
  tenantBusinessAddressCountrySchema,
} from './containers/tenantBusinessAddressCountry.js';
import {
  TenantBusinessCity,
  tenantBusinessCitySchema,
} from './containers/tenantBusinessCity.js';
import {
  TenantBusinessDba,
  tenantBusinessDbaSchema,
} from './containers/tenantBusinessDba.js';
import {
  TenantBusinessLegalEntityIdentifier,
  tenantBusinessLegalEntityIdentifierSchema,
} from './containers/tenantBusinessLegalEntityIdentifier.js';
import {
  TenantBusinessLegalName,
  tenantBusinessLegalNameSchema,
} from './containers/tenantBusinessLegalName.js';
import {
  TenantBusinessState,
  tenantBusinessStateSchema,
} from './containers/tenantBusinessState.js';
import {
  TenantBusinessStreetAddress1,
  tenantBusinessStreetAddress1Schema,
} from './containers/tenantBusinessStreetAddress1.js';
import {
  TenantBusinessStreetAddress2,
  tenantBusinessStreetAddress2Schema,
} from './containers/tenantBusinessStreetAddress2.js';
import {
  TenantCountry,
  tenantCountrySchema,
} from './containers/tenantCountry.js';
import {
  TenantWebhookUrl,
  tenantWebhookUrlSchema,
} from './containers/tenantWebhookUrl.js';
import { Data8, data8Schema } from './data8.js';

export interface Tenant {
  /** Unique identifier for the tenant */
  id: string;
  /** Workspace ID the tenant belongs to */
  workspaceId: string;
  /** Legal business name */
  businessLegalName: TenantBusinessLegalName;
  /** DBA - Doing Business As */
  businessDba: TenantBusinessDba;
  /** Country code in ISO 3166-1 format */
  businessAddressCountry: TenantBusinessAddressCountry;
  /** Street address line 1 (for businesses). */
  businessStreetAddress1: TenantBusinessStreetAddress1;
  /** Street address line 2 (for businesses). */
  businessStreetAddress2: TenantBusinessStreetAddress2;
  /** City (for businesses). */
  businessCity: TenantBusinessCity;
  /** State/region (for businesses). */
  businessState: TenantBusinessState;
  /** Legal Entity Identifier (for businesses). */
  businessLegalEntityIdentifier: TenantBusinessLegalEntityIdentifier;
  /** Country code derived from business address */
  country: TenantCountry;
  /** Webhook URL for payment creation notifications */
  webhookUrl: TenantWebhookUrl;
  /** Creation timestamp in ISO 8601 format */
  createdAt: string;
  /** Last update timestamp in ISO 8601 format */
  updatedAt: string;
}

export namespace Tenant {
  /**
   * Validation method to check if the given Tenant instance is also a Data8.
   */
  export function isData8(value: Tenant): value is Data8 {
    return isMappedValueValidForSchema(value, data8Schema);
  }
}

export const tenantSchema: Schema<Tenant> = lazy(() =>
  object({
    id: ['id', string()],
    workspaceId: ['workspace_id', string()],
    businessLegalName: ['business_legal_name', tenantBusinessLegalNameSchema],
    businessDba: ['business_dba', tenantBusinessDbaSchema],
    businessAddressCountry: [
      'business_address_country',
      tenantBusinessAddressCountrySchema,
    ],
    businessStreetAddress1: [
      'business_street_address1',
      tenantBusinessStreetAddress1Schema,
    ],
    businessStreetAddress2: [
      'business_street_address2',
      tenantBusinessStreetAddress2Schema,
    ],
    businessCity: ['business_city', tenantBusinessCitySchema],
    businessState: ['business_state', tenantBusinessStateSchema],
    businessLegalEntityIdentifier: [
      'business_legal_entity_identifier',
      tenantBusinessLegalEntityIdentifierSchema,
    ],
    country: ['country', tenantCountrySchema],
    webhookUrl: ['webhook_url', tenantWebhookUrlSchema],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
  })
);
