/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Data8, data8Schema } from './data8.js';

export interface TenantResponse {
  data: Data8;
}

export const tenantResponseSchema: Schema<TenantResponse> = lazy(() =>
  object({ data: ['data', data8Schema] })
);
