/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

export interface TenantApiCredentials {
  /** Auth0 M2M Client ID */
  clientId: string;
  /** Auth0 M2M Client Secret (only shown once!) */
  clientSecret: string;
  /** Auth0 token endpoint URL */
  tokenEndpoint: string;
  /** API audience for token requests */
  audience: string;
}

export const tenantApiCredentialsSchema: Schema<TenantApiCredentials> = object({
  clientId: ['client_id', string()],
  clientSecret: ['client_secret', string()],
  tokenEndpoint: ['token_endpoint', string()],
  audience: ['audience', string()],
});
