/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, Schema } from '../schema.js';
import { Tenant, tenantSchema } from './tenant.js';

export interface TenantListResponse {
  /** List of tenants */
  data: Tenant[];
}

export const tenantListResponseSchema: Schema<TenantListResponse> = lazy(() =>
  object({ data: ['data', array(tenantSchema)] })
);
