/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  number,
  object,
  optional,
  Schema,
  string,
} from '../schema.js';
import {
  TransferStepCompletedAt,
  transferStepCompletedAtSchema,
} from './containers/transferStepCompletedAt.js';
import {
  TransferStepConfirmedAt,
  transferStepConfirmedAtSchema,
} from './containers/transferStepConfirmedAt.js';
import {
  TransferStepFailedAt,
  transferStepFailedAtSchema,
} from './containers/transferStepFailedAt.js';
import {
  TransferStepFinalizedAt,
  transferStepFinalizedAtSchema,
} from './containers/transferStepFinalizedAt.js';
import {
  TransferStepFromAccountAssetId,
  transferStepFromAccountAssetIdSchema,
} from './containers/transferStepFromAccountAssetId.js';
import {
  TransferStepFromAccountId,
  transferStepFromAccountIdSchema,
} from './containers/transferStepFromAccountId.js';
import {
  TransferStepProviderKey,
  transferStepProviderKeySchema,
} from './containers/transferStepProviderKey.js';
import {
  TransferStepSubmittedAt,
  transferStepSubmittedAtSchema,
} from './containers/transferStepSubmittedAt.js';
import {
  TransferStepToAccountAssetId,
  transferStepToAccountAssetIdSchema,
} from './containers/transferStepToAccountAssetId.js';
import {
  TransferStepToAccountId,
  transferStepToAccountIdSchema,
} from './containers/transferStepToAccountId.js';
import {
  TransferStepTransactionHash,
  transferStepTransactionHashSchema,
} from './containers/transferStepTransactionHash.js';
import { Fee1, fee1Schema } from './fee1.js';
import { StatusEnum, statusEnumSchema } from './statusEnum.js';
import { StepTypeEnum, stepTypeEnumSchema } from './stepTypeEnum.js';

export interface TransferStep {
  /** Unique identifier for the step. */
  id: string;
  /** ID of the parent payment/transfer. */
  transferId: string;
  /** Step sequence number (0-based or 1-based). */
  stepSequence: number;
  /** Step type: 'stablecoin_transfer', 'offramp', 'onramp', 'fiat_transfer'. */
  stepType: StepTypeEnum;
  /** Source account asset ID for this step. */
  fromAccountAssetId?: TransferStepFromAccountAssetId;
  /** Amount sent in this step. */
  fromAmount: string;
  /** Currency code sent in this step. */
  fromCurrency: string;
  /** Destination account asset ID for this step. */
  toAccountAssetId?: TransferStepToAccountAssetId;
  /** Amount received in this step. */
  toAmount: string;
  /** Currency code received in this step. */
  toCurrency: string;
  /** Blockchain transaction hash (for crypto steps). */
  transactionHash?: TransferStepTransactionHash;
  /** List of fees associated with this step. */
  fees?: Fee1[];
  /** Provider key used for this step (if applicable). */
  providerKey?: TransferStepProviderKey | null;
  /** Step status: 'created', 'submitted', 'confirmed', 'finalized', 'failed'. */
  status: StatusEnum;
  /** Array of reasons explaining the current status (if any). */
  statusReasons?: (string | null)[] | null;
  /** Submitted timestamp. */
  submittedAt?: TransferStepSubmittedAt;
  /** Confirmed timestamp. */
  confirmedAt?: TransferStepConfirmedAt;
  /** Finalized timestamp. */
  finalizedAt?: TransferStepFinalizedAt;
  /** Completed timestamp. */
  completedAt?: TransferStepCompletedAt;
  /** Failed timestamp. */
  failedAt?: TransferStepFailedAt;
  /** ISO 8601 timestamp of creation. */
  createdAt: string;
  /** ISO 8601 timestamp of last update. */
  updatedAt: string;
  /** Source account ID for this step. */
  fromAccountId?: TransferStepFromAccountId;
  /** Destination account ID for this step. */
  toAccountId?: TransferStepToAccountId;
}

export const transferStepSchema: Schema<TransferStep> = lazy(() =>
  object({
    id: ['id', string()],
    transferId: ['transfer_id', string()],
    stepSequence: ['step_sequence', number()],
    stepType: ['step_type', stepTypeEnumSchema],
    fromAccountAssetId: [
      'from_account_asset_id',
      optional(transferStepFromAccountAssetIdSchema),
    ],
    fromAmount: ['from_amount', string()],
    fromCurrency: ['from_currency', string()],
    toAccountAssetId: [
      'to_account_asset_id',
      optional(transferStepToAccountAssetIdSchema),
    ],
    toAmount: ['to_amount', string()],
    toCurrency: ['to_currency', string()],
    transactionHash: [
      'transaction_hash',
      optional(transferStepTransactionHashSchema),
    ],
    fees: ['fees', optional(array(fee1Schema))],
    providerKey: [
      'provider_key',
      optional(nullable(transferStepProviderKeySchema)),
    ],
    status: ['status', statusEnumSchema],
    statusReasons: [
      'status_reasons',
      optional(nullable(array(nullable(string())))),
    ],
    submittedAt: ['submitted_at', optional(transferStepSubmittedAtSchema)],
    confirmedAt: ['confirmed_at', optional(transferStepConfirmedAtSchema)],
    finalizedAt: ['finalized_at', optional(transferStepFinalizedAtSchema)],
    completedAt: ['completed_at', optional(transferStepCompletedAtSchema)],
    failedAt: ['failed_at', optional(transferStepFailedAtSchema)],
    createdAt: ['created_at', string()],
    updatedAt: ['updated_at', string()],
    fromAccountId: [
      'from_account_id',
      optional(transferStepFromAccountIdSchema),
    ],
    toAccountId: ['to_account_id', optional(transferStepToAccountIdSchema)],
  })
);
