/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema.js';

/** Optional Turnkey stamp data for server-side signing */
export interface TurnkeyStamp {
  stampHeaderName: string;
  stampHeaderValue: string;
  turnkeyBody: string;
}

export const turnkeyStampSchema: Schema<TurnkeyStamp> = object({
  stampHeaderName: ['stampHeaderName', string()],
  stampHeaderValue: ['stampHeaderValue', string()],
  turnkeyBody: ['turnkeyBody', string()],
});
