/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for TypeEnum
 */
export enum TypeEnum {
  FiatBank = 'fiat_bank',
  StablecoinEthereum = 'stablecoin_ethereum',
  StablecoinSolana = 'stablecoin_solana',
  StablecoinStellar = 'stablecoin_stellar',
}

/**
 * Schema for TypeEnum
 */
export const typeEnumSchema: Schema<TypeEnum> = stringEnum(TypeEnum);
