/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { Schema, stringEnum } from '../schema.js';

/**
 * Enum for Type3Enum
 */
export enum Type3Enum {
  StablecoinEthereum = 'stablecoin_ethereum',
  StablecoinSolana = 'stablecoin_solana',
  StablecoinStellar = 'stablecoin_stellar',
}

/**
 * Schema for Type3Enum
 */
export const type3EnumSchema: Schema<Type3Enum> = stringEnum(Type3Enum);
