/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema, string } from '../schema.js';
import {
  UpdateTenantRequestBusinessAddressCountry,
  updateTenantRequestBusinessAddressCountrySchema,
} from './containers/updateTenantRequestBusinessAddressCountry.js';
import {
  UpdateTenantRequestBusinessDba,
  updateTenantRequestBusinessDbaSchema,
} from './containers/updateTenantRequestBusinessDba.js';
import {
  UpdateTenantRequestWebhookUrl,
  updateTenantRequestWebhookUrlSchema,
} from './containers/updateTenantRequestWebhookUrl.js';

export interface UpdateTenantRequest {
  /** Updated legal business name. */
  businessLegalName?: string;
  /** Updated DBA name. */
  businessDba?: UpdateTenantRequestBusinessDba;
  /** Updated business country code. */
  businessAddressCountry?: UpdateTenantRequestBusinessAddressCountry;
  /** Updated webhook URL. */
  webhookUrl?: UpdateTenantRequestWebhookUrl;
}

export const updateTenantRequestSchema: Schema<UpdateTenantRequest> = lazy(() =>
  object({
    businessLegalName: ['business_legal_name', optional(string())],
    businessDba: [
      'business_dba',
      optional(updateTenantRequestBusinessDbaSchema),
    ],
    businessAddressCountry: [
      'business_address_country',
      optional(updateTenantRequestBusinessAddressCountrySchema),
    ],
    webhookUrl: ['webhook_url', optional(updateTenantRequestWebhookUrlSchema)],
  })
);
