/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, optional, Schema } from '../schema.js';
import {
  ClassificationEnum,
  classificationEnumSchema,
} from './classificationEnum.js';
import {
  UpdateCounterpartyRequestBusinessAddressCountry,
  updateCounterpartyRequestBusinessAddressCountrySchema,
} from './containers/updateCounterpartyRequestBusinessAddressCountry.js';
import {
  UpdateCounterpartyRequestBusinessDba,
  updateCounterpartyRequestBusinessDbaSchema,
} from './containers/updateCounterpartyRequestBusinessDba.js';
import {
  UpdateCounterpartyRequestBusinessLegalName,
  updateCounterpartyRequestBusinessLegalNameSchema,
} from './containers/updateCounterpartyRequestBusinessLegalName.js';
import {
  UpdateCounterpartyRequestIndividualAddressCountry,
  updateCounterpartyRequestIndividualAddressCountrySchema,
} from './containers/updateCounterpartyRequestIndividualAddressCountry.js';
import {
  UpdateCounterpartyRequestIndividualFirstName,
  updateCounterpartyRequestIndividualFirstNameSchema,
} from './containers/updateCounterpartyRequestIndividualFirstName.js';
import {
  UpdateCounterpartyRequestIndividualLastName,
  updateCounterpartyRequestIndividualLastNameSchema,
} from './containers/updateCounterpartyRequestIndividualLastName.js';
import {
  UpdateCounterpartyRequestTenantId,
  updateCounterpartyRequestTenantIdSchema,
} from './containers/updateCounterpartyRequestTenantId.js';

export interface UpdateCounterpartyRequest {
  /** Classification: 'individual' or 'business'. */
  classification?: ClassificationEnum;
  /** Updated tenant ID. */
  tenantId?: UpdateCounterpartyRequestTenantId;
  /** Updated first name. Secure field, returned based on include_secure. */
  individualFirstName?: UpdateCounterpartyRequestIndividualFirstName;
  /** Updated last name. Secure field, returned based on include_secure. */
  individualLastName?: UpdateCounterpartyRequestIndividualLastName;
  /** Updated individual country code. */
  individualAddressCountry?: UpdateCounterpartyRequestIndividualAddressCountry;
  /** Updated business legal name. */
  businessLegalName?: UpdateCounterpartyRequestBusinessLegalName;
  /** Updated business DBA. */
  businessDba?: UpdateCounterpartyRequestBusinessDba;
  /** Updated business country code. */
  businessAddressCountry?: UpdateCounterpartyRequestBusinessAddressCountry;
}

export const updateCounterpartyRequestSchema: Schema<UpdateCounterpartyRequest> = lazy(
  () =>
    object({
      classification: ['classification', optional(classificationEnumSchema)],
      tenantId: [
        'tenant_id',
        optional(updateCounterpartyRequestTenantIdSchema),
      ],
      individualFirstName: [
        'individual_first_name',
        optional(updateCounterpartyRequestIndividualFirstNameSchema),
      ],
      individualLastName: [
        'individual_last_name',
        optional(updateCounterpartyRequestIndividualLastNameSchema),
      ],
      individualAddressCountry: [
        'individual_address_country',
        optional(updateCounterpartyRequestIndividualAddressCountrySchema),
      ],
      businessLegalName: [
        'business_legal_name',
        optional(updateCounterpartyRequestBusinessLegalNameSchema),
      ],
      businessDba: [
        'business_dba',
        optional(updateCounterpartyRequestBusinessDbaSchema),
      ],
      businessAddressCountry: [
        'business_address_country',
        optional(updateCounterpartyRequestBusinessAddressCountrySchema),
      ],
    })
);
