/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface UpdatePaymentRequest {
  /** ID of the account originating the payment. */
  originatorAccountId: string;
  /** ID of the source account (e.g., wallet). */
  sourceAccountId: string;
  /** ID of the beneficiary account. */
  beneficiaryAccountId: string;
  /** Optional external reference ID to update. */
  organizationReferenceId?: string;
}

export const updatePaymentRequestSchema: Schema<UpdatePaymentRequest> = object({
  originatorAccountId: ['originator_account_id', string()],
  sourceAccountId: ['source_account_id', string()],
  beneficiaryAccountId: ['beneficiary_account_id', string()],
  organizationReferenceId: ['organization_reference_id', optional(string())],
});
