/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, optional, Schema, string } from '../schema.js';

export interface UpdateAccountRequest {
  /** New name for the account. */
  name?: string;
}

export const updateAccountRequestSchema: Schema<UpdateAccountRequest> = object({
  name: ['name', optional(string())],
});
