/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Data8, data8Schema } from './data8.js';

export interface UpdateTenantResponse {
  data: Data8;
}

export const updateTenantResponseSchema: Schema<UpdateTenantResponse> = lazy(
  () => object({ data: ['data', data8Schema] })
);
