/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { lazy, object, Schema } from '../schema.js';
import { Data, dataSchema } from './data.js';

export interface UpdateCounterpartyResponse {
  data: Data;
}

export const updateCounterpartyResponseSchema: Schema<UpdateCounterpartyResponse> = lazy(
  () => object({ data: ['data', dataSchema] })
);
