/**
 * Tesser API (v1)Lib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  accessTokenAuthenticationProvider,
  compositeAuthenticationProvider,
} from './authentication.js';
import { Configuration } from './configuration.js';

export function createAuthProviderFromConfig(config: Partial<Configuration>) {
  const authConfig = {
    bearer:
      config.bearerAuthCredentials &&
      accessTokenAuthenticationProvider(config.bearerAuthCredentials),
  };

  return compositeAuthenticationProvider<
    keyof typeof authConfig,
    typeof authConfig
  >(authConfig);
}
